### ISSUE TITLE
Error to correct in master species dictionary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#799] opened 2020-02-19 10:34 UTC
@sacrevert asked me to change the vernacular name for a moss species from "Redshank" to Redshank Moss". I did this by editing the taxa via the warehouse interface. Wherever "Redshank" appeared in the common name box I edited it to "Redshank Moss" and saved, e.g. on this entry:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/114338

However, this appears to have produce two results that I was not expecting.

There are now five names that relate to this one taxon, the fifth of which seems to be a duplicate of the vernacular name, and seems to have been created as a result of the edits I did - I don't understand how.

And all five of those names now give the vernacular name as the preferred name - I don't understand how.

This file shows the relevant entries from the tables cache_taxa_taxon_lists and taxa:

[Redshank Moss problem.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/4224488/Redshank.Moss.problem.xlsx)

The query I used to show the cache_taxa_taxon_lists data is:
`SELECT cttl.id AS taxa_taxon_list_id, cttl.taxon_list_id, ttl.taxon_id, cttl.cache_created_on, cttl.cache_updated_on, cttl.preferred, cttl.allow_data_entry, cttl.preferred_taxa_taxon_list_id, cttl.parent_id, cttl.taxon, cttl.authority, cttl.preferred_taxon, cttl.preferred_authority, cttl.external_key
FROM cache_taxa_taxon_lists cttl
JOIN taxa_taxon_lists ttl ON cttl.id = ttl.id
WHERE cttl.taxon_list_id=15 and (cttl.taxon = 'Redshank Moss' OR cttl.taxon = 'Ceratodon purpureus' OR cttl.preferred_taxon = 'Redshank Moss'OR cttl.preferred_taxon = 'Ceratodon purpureus')
ORDER BY cttl.id`

The query I used to show the taxa data is:
`SELECT *
FROM taxa
WHERE id IN (114338,114339,114340,305174,385700)
ORDER BY id`

Please can you remove the duplicated vernacular name, and reset things so that the preferred taxon for all these four/five names is:
"Ceratodon purpureus", cttl.id = 114338, taxa.id = 114338

Marking as urgent to prevent the duplicated name and incorrect use of vernacular as preferred from causing issues elsewhere.

If it's straightforward to explain what I did wrong that would be appreciated. I'll stop trying to make edits to the species lists.

**Comment by johnvanbreda** [comment] 2020-02-19 12:02
I've cleaned up the data - marking this as non-urgent but leaving open as the underlying bug will need to be looked into.

**Comment by johnvanbreda** [comment] 2020-04-06 09:13
I've been unable to reproduce this on my local warehouse or the devwarehouse. Please re-open if you manage to reproduce.

**Closed by johnvanbreda** 2020-04-06 09:13 UTC
Labels: maintenance, scale:small
