### ISSUE TITLE
iRecord - Verify showing repeated timeout / query failed

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1005] opened 2021-02-09 09:10 UTC
Error  The website encountered an unexpected error. Please try again later.
Error message
PDOException: SQLSTATE[HY000] [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in lock_may_be_available() (line 167 of D:\websites\irecord\includes\lock.inc).

also 'ElasticSearch query failed'

**Comment by BirenRathod** [comment] 2021-02-09 09:14
@DavidHepper , @johnvanbreda @kitenetter Our database server is down at present and UKCEH's IT helpdesk team is looking into this.

**Comment by kitenetter** [comment] 2021-02-09 17:11
Latest update is that this was caused by a hardware failure. Measures have been taken to keep systems running, and replacement hardware should be installed tomorrow. Closing.

**Closed by kitenetter** 2021-02-09 17:11 UTC
