### ISSUE TITLE
Status mismatch - Not accepted or incorrect ?  Discrepancy on records

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#596] opened 2019-05-09 20:08 UTC
Looking at some records today on the old grid, it appears there is a mismatch with some records where the status displayed on the grid does not match that of the record.

All these records appear to have been actioned with the status button "Set to not accepted: Unable to verify" or "one Red X".  However, a good number of records in the grid that display "one Red X" on the grid have the status displayed on the record details as "not accepted: incorrect".  This is the status that should be applied to a record actions with the "Two red XX" button.

Examples:
As expected.  One red X and status "Not accepted, unable to verify" - 10033726 and 10033723

Mismatched:  One red X and status "Not accepted: incorrect" - 10052388 and 10062399

Looking at the same records via Elastisearch, these exemplar records have the correct "new style" status icons on the grid that match the details on the record.   It is also noticeable on the old grid that there are two slightly different colours of the "One red X" displayed on the grid which correspond to the two different record statuses.  Is this a data problem or just down to the original verification grid not displaying the "Two Red Xx" icon properly due to lack of space or something similar?

**Comment by johnvanbreda** [comment] 2019-05-10 08:13
This is not a data problem - the status icons in the grid have only ever differentiated incorrect records from other not accepted statuses by using a stronger red colour. Not accepted : unable to verify and the not accepted standalone statuses have both always appeared using the same icon.

@kitenetter it would be nice to standardise the icon set in all places. The new ones on Elasticsearch use the Font Awesome free icon collection so it would be nice to stick to ones available in that set.

**Comment by kitenetter** [comment] 2019-05-20 11:08
The old icons used for the verifier's choices were:

![image](https://user-images.githubusercontent.com/16039111/58017375-fb1cf300-7af7-11e9-8f19-17999fd9e82c.png)

The new ones are:

![image](https://user-images.githubusercontent.com/16039111/58017090-42ef4a80-7af7-11e9-9c74-681192a31611.png)

(It looks like the new icon for "Accepted: correct" is currently failing to display correctly?)

I agree that it is good to standardise these if we can. But the downside to standardising with the new ones rather than the old ones is that various recording schemes and other places have produced guidance on using iRecord that refers to (or screenshots) the old icons. And I do think the single- or double- cross or tick is easier to link to the verification statuses than changes in colour are.

I can see a double-tick icon in the Font Awesome set, but not a double-cross.

@johnvanbreda is there a reason why we need to drop the old icons?

**Comment by kitenetter** [comment] 2019-05-20 11:15
P.S. Having resisted change, I must admit I've never been entirely happy with the icons for the "plausible" category. The old one looks like a queried record, and the new one looks like the record has been accepted, when technically a plausible record is still within the "unconfirmed" category.

How about a simple minus-type symbol (i.e. just a straight line "-"), or a tilde "~" (which seems appropriate as it can mean "approximately")?

**Comment by MNSmith** [comment] 2019-05-20 16:08
Agree with Martins comments above.

**Comment by kitenetter** [comment] 2020-01-09 21:48
Aside from matters of taste over what the Plausible icon looks like, I don't think there is anything else to address here. Closing.

**Closed by kitenetter** 2020-01-09 21:48 UTC
