### ISSUE TITLE
When saving profile on user account, it has failed to synch with warehouse

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#307] opened 2018-01-15 18:53 UTC
Warehouse throws below error : 
general_errors.The system attempted to use your user account details to register you as a user of the central records database, but a different person with email address,

**Comment by BirenRathod** [comment] 2018-01-16 11:19
I'm looking into this.

**Comment by JimBacon** [comment] 2018-01-22 09:29
The full error message is 

> The system attempted to use your user account details to register you as a user of the central records database, but a different person with email address user@example.com already exists. 

It occurs when a user tries to register with iRecord when they already have an account on the warehouse with the same email address but a different first name + surname.

**Comment by BirenRathod** [comment] 2018-01-23 14:01
In this case user created on warehouse via NPMS and than tried to register via iRecord and failed to get indicia warehouse id. 

The actual error message is 

general_error.Undefined index:matches

**Comment by johnvanbreda** [comment] 2018-03-26 09:02
Hi @BirenRathod, I can't reproduce this. Are you able to specify clear steps as to how to get it to go wrong?

**Comment by BirenRathod** [comment] 2018-03-26 09:49
This particular one...

1. Search duplicate user from the database and iRecord.
2. First delete that user from people table & then delete from users table.
3. save original user profile form iRecord.

Problem with this user (Peter Stroh) is that it had registered with same name like Peter Stroh but emails are almost identical. one was (peter.stroh@bsbi.org & second with peter.stroh@bsbi.org.uk). So if system try to update record in user_identifiers table by using query like (peter.stroh%), it throws an error unless you update all records with just one id which you did other day.

**Comment by kitenetter** [comment] 2018-08-08 11:26
I think this is resolved now, see #352 - closing

**Closed by kitenetter** 2018-08-08 11:26 UTC
Labels: Urgent
