### ISSUE TITLE
Species download reports in Darwin Core Archive format

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#304] opened 2018-01-08 15:47 UTC
See attached (produced by Martin Harvey) for issues to be addressed

[NBN Atlas upload requirements 2018 1 8.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/1612127/NBN.Atlas.upload.requirements.2018.1.8.docx)

**Comment by kitenetter** [comment] 2018-01-31 15:31
There is an additional requirement from Natural England, who wish to be able to identify datasets linked to particular survey codes within the overall set of data sent to NBN. The proposal is that the NE data will be added to an NE-specific survey structure within iRecord, and that the structure will include a field for "Survey reference" (this field to be populated by NE staff at the point of data entry/upload).

On export to NBN, the "Survey reference" field would need to be mapped to a Darwin term. There are (at least) two possible candidates:
- collectionCode (which is seen as equivalent to the old Gateway "SurveyKey")
- catalogNumber (which is seen as equivalent to the old Gateway "SampleKey")

Of those, collectionCode seems the most appropriate.

I can see two options:
1. Include collectionCode as a standard field in all NBN exports (but this field will be empty for most datasets)
2. Set up an export report specific to the NE datasets

**Comment by DavidHepper** [comment] 2018-01-31 17:39
With remarkable timing I support your Option 2, to make this more general. I've received (yesterday) from BTO their Odonata records, for verification in iRecord by dragonfly experts. Andy Musgrove (BTO) and I would like to retain BTO's RECORDKEY value in a separate column, for traceability. This requires the addition of similar fields to iRecord for use only when importing data from another organisation. I suggested **SourceSurvey** and **SourceRecID**. **SurveyKey** and **SampleKey** are also clear. whereas the two Darwin terms proposed are really obscure. If they're the best for the job could we make them standard in iRecord and just document them carefully? 
David

**Comment by johnvanbreda** [comment] 2018-02-02 15:37
Questions from my perspective:
1) What to do about licence for records which have no explicit licence attached?
2) For the recordedBy field, we have a variety of formats due to the heterogeneous nature of our datasets. How important is the formatting in this field?
3) How to handle the rightsHolder field.
4) gridReference - suggest using the output_grid_ref for consistency and because it copes with blurring. If we do that, then the coordinateUncertaintyInMeters is already accounted for so can be set to 0?
5) datasetName - would this be just the website title (e.g. iRecord) or include the survey dataset (iRecord General records)?
6) How to handle georeferenceVerificationStatus? Either set to the same as the identificationVerificationStatus on the assumption the verified checked both, or leave as "Unconfirmed"? Same question for georeferenceVerificationStatus2.
7) individualCount - need to check if this is numeric only. DwC documents don't make this clear.
8) Should occurrenceRemarks include any comment made at the sample level?

**Comment by johnvanbreda** [comment] 2018-02-14 14:50
Beta functionality now on iRecord.

**Comment by kitenetter** [comment] 2018-02-19 12:02
@johnvanbreda is it possible to see the beta functionality? Do we still need to resolve the questions you listed above?

**Comment by johnvanbreda** [comment] 2018-02-19 12:51
@kitenetter yes - did you see my separate email with information about this? We do need to answer the questions above at some point but it is good enough to test.

**Comment by kitenetter** [comment] 2018-02-19 13:12
@johnvanbreda had seen it, had forgotten about it! Will give that a try, thanks.

**Comment by johnvanbreda** [comment] 2018-02-23 13:54
Will split this issue out into sub-issues in https://github.com/BiologicalRecordsCentre/iRecord/milestone/4.

**Comment by kitenetter** [comment] 2018-03-18 16:31
Typos in the iRecord export report (spotted by Andy Webb):
- decimaLatitude should be decimalLatitude
- decimaLongitude should be decimalLongitude

**Comment by johnvanbreda** [comment] 2018-03-21 13:34
Lat and long column names have been fixed in the develop branch of code.

**Closed** 2018-07-23 14:15 UTC
Labels: beta released
