### ISSUE TITLE
Elastisearch - Previous & Next buttons II

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#577] opened 2019-04-19 12:46 UTC
If you clear a grid of records selected by typing a name in the species search box the "previous" and "next" button do not function.  Problem related to similar issues logged elsewhere?

**Comment by kitenetter** [comment] 2020-01-09 22:16
Unable to reproduce this - closing for now but let us have more information if it is still a problem.

**Closed by kitenetter** 2020-01-09 22:16 UTC
