### ISSUE TITLE
Inconsistent application of rulesets

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#507] opened 2019-03-03 16:23 UTC
On my verification page for soldierflies and allies I'm seeing some species being flagged as hard to ID in some cases, and as passing all verification checks in others. I can't see any reason for this to be inconsistent, and it makes me nervous about applying bulk verification.

![image](https://user-images.githubusercontent.com/16039111/53698131-7d86f800-3dd0-11e9-804e-79363eb06e45.png)

**Comment by kitenetter** [comment] 2019-03-11 22:59
Same issue applies to Berkshire moths, and presumably elsewhere. I'm rather worried by this one as it could be affecting substantial numbers of records that are bulk verified, and maybe some of the auto-verification as well?

**Comment by johnvanbreda** [comment] 2019-03-12 07:50
Whether this is correct or not I'm not sure, but it is as designed. Richard has previously had verified records of this species so the ID difficulty rule does not trigger, in order to avoid excessive notifications.

**Comment by kitenetter** [comment] 2019-03-12 09:26
Ah, I didn't realise the rules were being over-ridden for ID difficulty, I thought it was just distribution. Are these ruleset over-rides documented anywhere (apologies if you've told me that before and I've forgotten)?

I can think of at least one area where this is problematic: where spreadsheets are imported containing records from many different recorders the ID difficulty over-ride is being applied to the user account for the importer, and takes no notice of the actual recorders.

That's fine for distribution over-rides, but the ID difficulty flag interacts with the experience/knowledge of the recorder concerned, and I'm not sure it should ever get over-ridden in the same way.

Actions:
- @johnvanbreda can you let me know if the current over-ride process is documented
- @kitenetter to document this if it isn't already (and to start scoping out a review of how the rulesets are currently being applied for verification within iRecord)

**Comment by johnvanbreda** [comment] 2019-03-12 12:22
@kitenetter - no, this feature is obvious in the code but not formally documented anywhere.
Is the solution to prevent the notification going to the user in these cases rather than preventing the rule from firing as it does now?

**Comment by kitenetter** [comment] 2019-03-12 12:57
If I'm understanding that correctly then I think the answer is yes! I definitely think that for the verification grid we should **not** show records of difficult species as having passed the checks, as that makes it impossible to use the ID rules to filter out records consistently for verification.

Regarding notifications to recorders, I think it probably is best to prevent multiple notifications about the same species to the same recorder. However, I've just had feedback from another verifier asking if we can make the ID difficulty notifications more prominent, because recorders are ignoring them (e.g. continuing to send in photo records of species that require dissection). I'll have a think about that but this might be one of those issues that is hard to resolve to everyone's satisfaction.

**Comment by kitenetter** [comment] 2019-04-15 20:58
@johnvanbreda said "this feature is obvious in the code but not formally documented anywhere". Can you let me know how I can view that code, or if it is easier copy the relevant section to me, or alternatively could @burkmarr look into this?

**Comment by kitenetter** [comment] 2019-06-10 13:37
@burkmarr have just assigned this to you - what I'm hoping is that you would be able to find the code that John refers to above and either turn that into some documentation about how the rulesets get over-ridden as new data accumulates, or copy the code to me for me to write up some documentation (which I'm very happy to do if the code is sufficiently readable for me to interpret it correctly) - thanks.

**Comment by burkmarr** [comment] 2019-06-10 15:28
@kitenetter I'll take a look.

**Comment by burkmarr** [comment] 2019-06-11 14:09
@kitenetter  I think I have located the code, but I don't think that it tells you any more than John has already outlined. @johnvanbreda  will correct me if I'm wrong, but I don't think this is one of a set of potential overrides - as far as I can tell, it's a one-off. I can point you to the code or send it to you if you like. From your comment above, it seems as though you would like a code change to prevent the override of difficult to ID species in the verification grid for users that have a verified record for that species. Do you want me to go ahead and work on that?

**Comment by kitenetter** [comment] 2019-06-11 15:35
@burkmarr I don't yet feel that I fully understand how the over-ride processes works. The record cleaner rules address three issues I think:
- difficulty of ID
- phenology
- distribution

My understanding is that within the iRecord context we now apply over-rides to these rule types as follows:
- difficulty of ID: according to the information earlier in this thread, if a given iRecord account has had a species accepted then that species is no longer flagged as being hard to ID. What I don't know is: how many times does the user-taxon combination need to be accepted before the rule is over-ridden?; does this apply to ALL levels of difficulty?; does this affect both the user's notifications and the pass/fail rules display on the verification page (I think it does)?
- phenology: I don't know if we are over-riding the out-of-season rules on the basis of previously accepted records for date periods; if we are, I'd like to know how many accepted records are needed for the rule to be over-ridden, whether this is applied per-user or per-taxon, and whether it is applied for each single day or if a broader period such as a week is used
- distribution: I believe we are over-riding distribution rules where a record falls in an area for which the taxon has had previous accepted records, but I'm not certain of: does this work at 10km square level?; how many accepted records in any given square are needed to trigger the over-ride?; is this linked applied per-user or per-taxon (I think it is per-taxon)?

If we can clarify exactly how the over-rides are behaving we can then decide on what, if anything, needs editing or reviewing.

**Comment by johnvanbreda** [comment] 2019-06-11 16:54
@burkmarr just in case you are looking somewhere else, the code is at https://github.com/Indicia-Team/warehouse/blob/master/modules/data_cleaner_identification_difficulty/plugins/data_cleaner_identification_difficulty.php. The comment in the query on line 65 explains that anyone who has successfully identified this species before won't be re-notified. That was done in response to concerns about over-notification, particularly from experienced recorders who saw the messages as insulting. You are right about this being a one off - it's just hard coded. There are similar efforts in the period within year and without polygon rules to avoid notifying when a species seems to be expanding it's range etc.

To answer @kitenetter's questions:

> difficulty of ID: according to the information earlier in this thread, if a given iRecord account has had a species accepted then that species is no longer flagged as being hard to ID. What I don't know is: how many times does the user-taxon combination need to be accepted before the rule is over-ridden?; does this apply to ALL levels of difficulty?; does this affect both the user's notifications and the pass/fail rules display on the verification page (I think it does)?

Yes, this applies to all difficulty levels and it occurs with just 1 successful ID by that user. Because this code affects the generation of the actual rule violation itself, no other functionality based on this rule violation will happen, including the flagging in verification, the notification or the subsequent email.

> phenology: I don't know if we are over-riding the out-of-season rules on the basis of previously accepted records for date periods; if we are, I'd like to know how many accepted records are needed for the rule to be over-ridden, whether this is applied per-user or per-taxon, and whether it is applied for each single day or if a broader period such as a week is used

Here's the code: https://github.com/Indicia-Team/warehouse/blob/master/modules/data_cleaner_period_within_year/plugins/data_cleaner_period_within_year.php. Around line 105, I can see that other records will qualify if in the same 10km square, within a week either side of the day in year, verified and with a matching stage where specified. The GROUP BY code starting around line 141 explains that you need at least 2 verified records matching these criteria to stop further violations.

> distribution: I believe we are over-riding distribution rules where a record falls in an area for which the taxon has had previous accepted records, but I'm not certain of: does this work at 10km square level?; how many accepted records in any given square are needed to trigger the over-ride?; is this linked applied per-user or per-taxon (I think it is per-taxon)?

Here's the code: https://github.com/Indicia-Team/warehouse/blob/master/modules/data_cleaner_without_polygon/plugins/data_cleaner_without_polygon.php. Around line 64 I can see the species is matched on external key, accepted and in the same grid square.  Line 78 confirms 2 records are required to stop the rule firing.

The original issue here was that ID rules don't fire for recorders who have successfully recorded something, but the lack of rule flags is frustrating for the verifiers who use the flags to filter the data. I think this is a separate issue to the exact criteria used to block raising of rule violations for without_polygon and period_within_year rules. These may need a tweak but I'm not aware of these criteria being a problem. The solution to the underlying problem therefore is to make the identification_difficulty rule violation fire in all cases, but move the filtering out of records where the recorder has successfully recorded something into the notification system instead. That way the flag will exist on the record, but the recorder won't get any repeat notifications.

You might argue that we should adopt the same principle for period_within_year and without_polygon, but I think they are a different case. For the ID difficulty, the adaptation of the system is to the competence of the recorder. For these rule types, the system is adapting to the rules either being plain wrong in the first place, or now so out of date as to not be useful (e.g. after a population expansion). I could imagine a side-project from this issue would be to write some more intelligent code to pick outliers out irrespective of the record cleaner rules. Maybe that's for a rainy day...

**Comment by burkmarr** [comment] 2019-06-19 15:02
@kitenetter - if you're in agreement with @johnvanbreda's analysis - particularly the last two paragraphs above - perhaps we could close this issue and raised a new one specifically to address this piece of work:

> The solution to the underlying problem therefore is to make the identification_difficulty rule violation fire in all cases, but move the filtering out of records where the recorder has successfully recorded something into the notification system instead. That way the flag will exist on the record, but the recorder won't get any repeat notifications.

I'm happy to be assigned to that and I can take a look and liaise with John.

**Comment by kitenetter** [comment] 2019-08-28 13:24
**ID difficulty:**
I do think that we should split out the notifications over-ride from the verification flag, which shouldn't be over-ridden. Will raise a new issue for this.

**Phenology:**
I feel that allowing a record to be unflagged if it is within seven days of an accepted record is too wide a date range, and I would propose that we reduce this to three days. I think we should only start over-riding rules on the basis that the typical phenology has shifted, rather than on the basis of occasional outlying records. Perhaps the ideal solution would be to do a more sophisticated phenology analysis, but in the meantime 3 days feels safer than 7 to me. What do you think @burkmarr @DavidRoy @johnvanbreda ?

**Distribution:**
I'm happy with how this is working.

I have added some documention on the rulesets to:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Procedures and guidance\REFERENCE Record Cleaner rules within iRecord.docx

Will close the current issue following feedback on the phenology period.

**Comment by johnvanbreda** [comment] 2019-08-28 14:58
@kitenetter I think it depends on whether you come with the mindset of a user who feels the rules are useful and would rather the occasional false rule notification than to miss out on some, vs another user who feels the rules are a waste of time and certainly doesn't want any erroneous notifications. Another thought - rather than reducing to 3 days, we could leave it at 7 days but only remove the flag if there are more accepted records inside that timeframe (e.g. > 10).

**Comment by kitenetter** [comment] 2019-08-28 15:10
@johnvanbreda my mindset is of a verifier who likes to be able to bulk verify species that pass the rules, and therefore gets nervous when the rules may not be sufficiently rigorous! 

My worry was that one or two outliers might appear in exceptional weather, and be correctly flagged as accepted records, and then this would lead to potentially incorrect records slipping through once the weather reverted to 'normal'. I don't have any strong feelings on whether we reduce the number of days or increase the threshold for number of records, I think either approach would reassure me!

**Comment by burkmarr** [comment] 2019-08-29 08:09
When I verify spider records I tend to completely ignore the phenology and range flags because they are triggered so often. That may just be a function of the spider rulesets being out of date. But the kind of tweaks suggested seem sensible to me. I've no strong feelings about days vs numbers.

**Comment by kitenetter** [comment] 2019-10-08 10:40
Phenology over-rides: having read through the above comments again, I think we should leave the follow John's suggestion to "leave [the timeframe] at 7 days but only remove the flag if there are more than 10 accepted records inside that timeframe".

I think that makes it less likely that one-off out-of-season records will lead to inappropriate relaxations in the phenology rules.

@burkmarr are you okay to make this change? I'll add it to the October milestone but feel free to move it to November if October is too full.

**Comment by burkmarr** [comment] 2019-10-08 12:54
@kitenetter - okay, I'll take a look soon.

MH:
> phenology: I don't know if we are over-riding the out-of-season rules on the basis of previously accepted records for date periods; if we are, I'd like to know how many accepted records are needed for the rule to be over-ridden, whether this is applied per-user or per-taxon, and whether it is applied for each single day or if a broader period such as a week is used.

JvB:
> Here's the code: https://github.com/Indicia-Team/warehouse/blob/master/modules/data_cleaner_period_within_year/plugins/data_cleaner_period_within_year.php. Around line 105, I can see that other records will qualify if in the same 10km square, within a week either side of the day in year, verified and with a matching stage where specified. The GROUP BY code starting around line 141 explains that you need at least 2 verified records matching these criteria to stop further violations.

MH:
> I feel that allowing a record to be unflagged if it is within seven days of an accepted record is too wide a date range, and I would propose that we reduce this to three days. I think we should only start over-riding rules on the basis that the typical phenology has shifted, rather than on the basis of occasional outlying records. Perhaps the ideal solution would be to do a more sophisticated phenology analysis, but in the meantime 3 days feels safer than 7 to me.

JvB:
> Another thought - rather than reducing to 3 days, we could leave it at 7 days but only remove the flag if there are more accepted records inside that timeframe (e.g. > 10).

MH:
> I think we should leave the follow John's suggestion to "leave [the timeframe] at 7 days but only remove the flag if there are more than 10 accepted records inside that timeframe

**Comment by burkmarr** [comment] 2019-10-17 14:30
@kitenetter and @johnvanbreda - this is the simplest of changes in the code, just changing 2 for 10 on line 147 in https://github.com/Indicia-Team/warehouse/blob/master/modules/data_cleaner_period_within_year/plugins/data_cleaner_period_within_year.php'

But I can see that this was changed from 3 to 2 a couple of years ago with a commit message 'stops raising rule violations if 2 present in same grid square rather than 3'. (https://github.com/Indicia-Team/warehouse/commit/a4a4dbf99a3483afaebddf4c1cf446a05c6d9fef)

So we've been here before but changed it in the other direction presumably in response to a percieved problem, e.g. too many notifications. So I want to double-check with you both before going ahead with it.

**Comment by johnvanbreda** [comment] 2019-10-17 14:36
Good question. There has definitely been pressure in the other direction in the past as from many recorder's perspective they don't like the rule messages. @kitenetter you are probably best placed to make the call here though.

**Comment by kitenetter** [comment] 2019-10-23 12:38
I have to admit that so far it is only me who is pushing for change on this one, but I do think we ought to prioritise verifiers' needs over users' needs in this case, and I think that the threshold of 2 records is too low. I'd be happy to compromise a bit and go for 6 records.

Alongside that we can try to communicate more clearly to people that they can control the notifications they receive. There is a Help page:
https://www.brc.ac.uk/irecord/control-emails

The notification emails that we send out do have a link "Click here to update your subscription settings." Perhaps we could reword to make that clearer:
"Click here to control which notifications you receive."

I'm not sure how to edit the notification text, please can @johnvanbreda advise if it isn't already obvious to @burkmarr.

**Comment by johnvanbreda** [comment] 2019-10-23 13:18
@burkmar the wording is in the file modules/notification_emails/plugins/notification_emails.php.

**Comment by burkmarr** [comment] 2019-10-24 14:03
Pull request made: https://github.com/Indicia-Team/warehouse/pull/337

**Closed** 2019-10-25 15:06 UTC
Labels: bug, code fixed awaiting release, verification
