### ISSUE TITLE
Elastic verification: lookup for redeterminations fails occasionally

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#697] opened 2019-10-12 11:17 UTC
On redetermining a record a window appears with an autocomplete lookup to add the new taxon name. Recently I've found that this works fine for a few redets, but every so often it stops working: I type in the taxon name I wish to use, and I get an egg-timer that fails to produce a list of species names to select from.

So far the only solution I have found is to refresh the page, which then means I have to reset any filtering/sorting options that I was previously using.

**Comment by MNSmith** [comment] 2019-10-13 10:54
Question - where is the re-det button for Elastisearch records.  I can see an "Edit this record" button, but not a "Redet" button.

**Comment by DavidRoy** [comment] 2019-10-13 10:58
It’s by the species name in the record details panel.  It took me a while to notice this too

**Comment by MNSmith** [comment] 2019-10-13 19:04
Thanks David.  I would prefer to see this button back up on the little action bar above the record details - if we ever get bulk redet facilities this is where the button really needs to be as well.

Could we have a different icon for this feature, at present the "Edit" and "Redet" buttons have the same icon / appearance.

**Comment by kitenetter** [comment] 2019-10-21 22:35
The lookup failure is a small bug, but I do find it very irritating when doing verification. You have to wait a long time to find out whether it has actually failed, or is just being slow, and then when it does fail it takes a long time to go through the page refresh and resetting of filters. If it is possible to have a refresh button just for the lookup, i.e. on the redet window, that will refresh things without having to reset the whole page, that would be brilliant!

**Comment by DavidHepper** [comment] 2019-10-22 08:40
I'm also a long-time supporter of manual refresh buttons. It is rare that I only want to filter on a single column header. The current refresh-on-leaving-field policy slows the system and puts unnecessary load on the server. It is hardly onerous to click a ![image](https://user-images.githubusercontent.com/24915271/67269998-abc85d80-f4af-11e9-938a-ee46d0ef93a3.png) button in this case and to reload the map.

**Comment by johnvanbreda** [comment] 2019-10-22 08:55
@kitenetter - can you create 2 separate issues for the move of the redet button and the idea of a reload button in David's last post which I think makes sense.

**Comment by johnvanbreda** [comment] 2019-10-22 08:57
Regarding the original error, which browser has the problem and are you able to find out if there is an associated JavaScript error in the developer tools?

**Comment by kitenetter** [comment] 2019-10-22 10:18
Browser was Firefox. I've just come to the end of my photo verifications for now so can't look for Javascript errors immediately.

**Comment by johnvanbreda** [comment] 2019-10-24 11:34
Ok, I'll wait then as I can't reproduce it. Let me know when you get a chance.

**Comment by kitenetter** [comment] 2020-01-09 21:08
@johnvanbreda the freezing of the redet species lookup is a constant feature for me, when using Firefox, and when having been verifying for a reasonably long period of time. I haven't yet managed to find a javascript error, can you remind me how I do that? Is it via "Inspector" or "Debugger"?:

![image](https://user-images.githubusercontent.com/16039111/72104770-0b523e80-3324-11ea-98f6-9ca416f3fdca.png)

**Comment by johnvanbreda** [comment] 2020-01-10 08:44
In FireFox -> Tools menu, Web Developer > Web Console.

**Comment by kitenetter** [comment] 2020-01-11 21:34
This has just happened again, and the error messages are:

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. verification
window.controllers/Controllers is deprecated. Do not use it for UA detection. js_1nEZUStSYISQnp68mZyw8ogbW-05lqLAudw6Blvp5qs.js:13269:417
TypeError: jQuery183047958919699179403_1578763955899 is not a function taxa_search:1:42
XML Parsing Error: not well-formed
Location: https://www.brc.ac.uk/irecord/ajaxproxy?node=&index=occurrence&user_id=50&sharing=editing
Line Number 1, Column 1: ajaxproxy:1:1
XML Parsing Error: syntax error
Location: https://www.brc.ac.uk/irecord/ajaxproxy?node=7614&index=list_verify&user_id=50&sharing=verification
Line Number 1, Column 1: 42 ajaxproxy:1:1
The script from “https://warehouse1.indicia.org.uk/index.php/services/data/ta…e444270cc0f2b12870ea493f376&taxon_list_id=15&_=1578778250756” was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type. verification
TypeError: item.language_iso is undefined verification:413:7

**Comment by johnvanbreda** [comment] 2020-01-13 10:24
@kitenetter -please can you:
1) Send me the HAR file.
2) Let me know what taxon you were searching for and exactly what time.
3) On the Network tab, look for the request to “https://warehouse1.indicia.org.uk/index.php/services/data/taxa_search" and click on it to see if you can find the actual error or response to this request. You can use Ctrl-F to search in the network requests list if that helps.

**Comment by kitenetter** [comment] 2020-01-17 23:56
At. 23:42 I tried to redetermine occurrence 10180693 from Chloromyia formosa to Microchrysa polita. The redet box opened, I typed in "mipol", nothing happened (no lookup list, no egg-timer).

The HAR file:

[www.brc.ac.uk_Archive [20-01-17 23-54-24].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4079686/www.brc.ac.uk_Archive.20-01-17.23-54-24.zip)

In the network list this is the request:
https://warehouse1.indicia.org.uk/index.php/services/data/taxa_search?callback=jQuery18306710927575137628_1579293675573&q=mipo&unsimplified=mipo&limit=21&timestamp=1579304797756&orderby=searchterm&mode=json&qfield=searchterm&auth_token=6aeb0120a38a136c068792d9d340a18ffe93d6ab&nonce=2aac3b90f46543dc806e669b0599255338ab6acc&taxon_list_id=15&_=1579304797758

And I think this is the response info?:

![image](https://user-images.githubusercontent.com/16039111/72653768-59022300-3984-11ea-8b7e-30e7b9cdaa04.png)

**Comment by johnvanbreda** [comment] 2020-01-20 10:11
Thanks @kitenetter. Did this happen just a few minutes after initially loading the verification page (as the HAR file seems to imply) or were you using the page for longer than that?

**Comment by kitenetter** [comment] 2020-01-20 10:15
Sorry John, I can't remember for certaing, but I think in this case I had left the computer on standby for a while after doing some verification earlier in th evening, then came back to it and refreshed the page, and then got the redet freeze.

Generally I would say that it usually happens after I have been verifying for some time.

**Comment by kitenetter** [comment] 2020-02-03 14:23
Check timing of appearance of error message

**Comment by kitenetter** [comment] 2022-02-03 11:43
I'm getting reports, and am experiencing myself, a continuing problem with the redet process. If I have been verifying for some time, and then go to redet a record, the look-up for species names fails and no redet can be done until the whole page is refreshed.

Do we still need more HAR files or other info to investigate further?

**Comment by kitenetter** [comment] 2022-12-01 22:20
Bumping this, which continues to be a frustration for verifiers. Not sure if it is related to the overall performance issues, but it seems to be a regular if not constant experience that if one is verifying for a longish period, the redet lookup stops working after a length of time.

Let me know if this would be better transferred to a new clean issue.

**Comment by kitenetter** [comment] 2023-04-21 16:35
This is still being reported by verifiers. Moving into May milestone.

**Comment by johnvanbreda** [comment] 2023-07-31 15:14
I've implemented a read token refresh in the develop branch so this should be fixed at the next full code update.

**Comment by johnvanbreda** [comment] 2023-09-20 14:38
Code now deployed.

**Closed by johnvanbreda** 2023-09-20 14:38 UTC
Labels: bug, code fixed awaiting release, verification
