### ISSUE TITLE
Add hyperlink to view record in email sent by verifiers

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#8] opened 2016-03-27 15:42 UTC
In emails sent to verifiers notifying them of recorder responses to queries, it would be good to include a hyperlink to the record itself (from Alan Stewart)

**Comment by kitenetter** [comment] 2016-07-11 22:00
Similarly, in auto-emails notifying recorders of comments on their records a hyperlink would facilitate responses to the comments

**Comment by johnvanbreda** [comment] 2016-08-31 13:48
Duplicate of https://github.com/Indicia-Team/warehouse/issues/186.

**Comment by johnvanbreda** [comment] 2016-08-31 15:04
This issue now coded in the development branch and tagged so that it will get released in the next version of the warehouse.

**Closed** 2016-10-05 11:24 UTC
Labels: enhancement
