### ISSUE TITLE
Verification new page - photo filtering not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#644] opened 2019-08-06 22:40 UTC
Reported by Stuart Roberts, replicated in my account: on the new verification page, if you select "Photos: Without", records with photos are being displayed alongside records without. In fact the "Without" filter looks like it is not having any affect at all.

**Comment by kitenetter** [comment] 2019-08-06 23:28
Various other things seem to have stopped working as well, including the ability to sort by chosen column heading, and the ability to use tick boxes to select multiple records. Is it useful to itemise such things or is this all part of the ongoing development of the new page?

**Comment by johnvanbreda** [comment] 2019-08-07 10:34
I've fixed the photos filter - I'd changed to a new way of storing media (so the licence data from iNat is kept alongside the photo) but forgotten to update this filter. 
I can't reproduce any of the other problems you mention though - can I have more details (e.g. browser?).

**Comment by kitenetter** [comment] 2019-08-07 10:44
I can't reproduce the other problems using Chrome on my work computer this morning. Last night they arose when I was using Firefox on my home computer, Will check again this evening.

**Comment by kitenetter** [comment] 2019-08-07 11:50
Okay, I've now reproduced the problem, using Chrome on my work computer. It arises if I use the grid column settings tool to change the selection of columns displayed on the grid. Having made and saved my choices, the column head sorting options no longer work, and the tick boxes are not available.

**Comment by johnvanbreda** [comment] 2019-08-07 12:24
Ok - I'd spotted this bug separately yesterday whilst working on ABLE, so it's fixed in the develop branch of the code and will be deployed soon.

**Closed** 2019-09-02 13:11 UTC
Labels: bug, code fixed awaiting release, scale:small, verification
