### ISSUE TITLE
Suggested species order when entering species name

### ISSUE THREAD

**Issue by cubitmg** [BiologicalRecordsCentre/iRecord#1511] opened 2023-06-20 12:50 UTC
I have just had a record for verification that had the species name as Clouded-bordered Brindle when the photo was for a Clouded Border. Two easily distinguished species. When I went in to redetermine it I found the issue which is that when the full name of the latter is typed in exactly, the former species' name appears before the latter's. This is despite the former having a hyphen between the first two words. Having both species names appear is good, but I would suggest that their order and default selected, should be based on best match for what is typed?
![SpeciesSelector](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/79d5aad5-bf58-4864-89b7-48bf4edba2fc)

I tried to test whether the same happened when entering a new record, but the page wont open and has an error. See second attachment.
![EnterRecordPostError](https://github.com/BiologicalRecordsCentre/iRecord/assets/65334323/b28f573c-0618-42e2-807b-44901b7280d8)

**Comment by johnvanbreda** [comment] 2023-06-26 17:22
@cubitmg The latter error was caused by server down-time last week so shouldn't happen again.

I've fixed the ordering of the taxa in the search for this scenario - the hyphen was being treated as a higher sort priority to the space. That's done in the code but will be released next time I do a full release.

**Comment by johnvanbreda** [comment] 2023-09-20 13:53
Now released so closing.

**Closed by johnvanbreda** 2023-09-20 13:53 UTC
Labels: code fixed awaiting release
