### ISSUE TITLE
Recent change to viewing "Experience" records is unhelpful

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#346] opened 2018-03-18 16:03 UTC
From the verification page, it is possible to view a recorder's records that have previously been accepted or not, by clicking on the blue numbers in the "Experience" tab. However, there are two changes to the behaviour of this that seem to be recent and are in my view unhelpful.

The first is that if I am verifying and have chosen "soldierflies" as my context, when the records page opens up from the experience tab it always defaults back to "Berkshire moths", and thus doesn't display the soldierfly records. I can change the filter on the records page but it's an extra mouse-click.

The second is that whereas previously I could use the "all Diptera" experience numbers to see records that had been accepted or rejected in **any** Diptera family, it now only shows records within the families that I verify. Previously it was very helpful to be able to see, for example, how many hoverfly records had been accepted or not from a recorder who has only recently started recording soldierflies.

**Comment by MNSmith** [comment] 2018-03-23 15:32
I would second what Martin has said above.

At present, the ability to look back over past records for a species or a group is not working for me, clicking on any of the numbers in the experience boxes returns an empty list

**Comment by johnvanbreda** [comment] 2018-04-05 13:51
I've committed a fix for the issue where the correct context isn't automatically chosen.

The 2nd issue about reviewing records outside your verification context is caused by the fact that we have switched to a report which is respecting verification permissions, because the previous generic report did not include records from some sites that don't expose records for reporting in iRecord, just verification (a recently fixed bug). Changing this is a bigger issue that probably warrants its own issue if you still feel it is relevant.

**Closed** 2018-04-05 14:44 UTC
Labels: bug
