### ISSUE TITLE
Unable to access warehouse via menus

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#463] opened 2018-12-20 18:07 UTC
Not sure if I'm being daft, but I can't find a way to get in to any of the warehouse options. The top level menus are all visible (Lookup lists, Custom attributes etc.) but when I click on the menus nothing happens.

This is for http://warehouse1.indicia.org.uk/index.php/

**Comment by BirenRathod** [comment] 2018-12-20 18:11
Blocking to access for non-admin users.

**Comment by DavidRoy** [comment] 2018-12-20 20:48
I raised this issue here https://github.com/Indicia-Team/warehouse/issues/313

A problem on Chrome but not IE for me

**Comment by johnvanbreda** [comment] 2018-12-21 08:39
Duplicate of https://github.com/Indicia-Team/warehouse/issues/313

**Closed by johnvanbreda** 2018-12-21 08:39 UTC
Labels: bug
