### ISSUE TITLE
Users' records failing to display

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#624] opened 2019-07-04 17:02 UTC
We had a report in the forums from two users whose records had disappeared from their "My records" view: https://www.brc.ac.uk/irecord/node/7653

I fixed this for each user through this procedure:
- Masquerade as user
- User account page shows "Your preferred locality for recording is ." (NB full stop but no county name).
- Edited user account (while still masquerading). "Where you record - Recording location" was apparently set to "<Please select>". I opened the dropdown list, reselected "<Please select>" and saved. 
- Account page is now no longer showing any text about preferred recording area, and records have reappeared in user's "My records" view.

The question is what the underlying problem is that caused the preferred location link to fail, and whether it might be affecting other users. I did wonder whether it related to the aggregate Sussex and Yorkshire counties, but I don't think we have yet made any change to those (#606).

And it doesn't appear to be related to #617 

Where does the user's choice of recording location get stored? Are we able to set up a query to look for users who are linked to a null location, or similar?

**Comment by burkmarr** [comment] 2019-07-09 17:22
The ids of the locations are stored in the Drupal DB @kitenetter. I can't see anything obvious. I wonder if the problem conditions for those two users is was carried into irecord_dev. If you can mail me their identities, I can check. Don't fix the problem on irecord_dev if it's present - I want to examine the underlying DB state. It's hard to investigate something like this if you can't reproduce it.

**Comment by kitenetter** [comment] 2019-07-16 20:24
@burkmarr the user names are "Dipper" and "Nev Wright". I've tried masquerading on the dev site but I just get an endless egg-timer, so haven't been able to check whether their records are visible on dev.

**Comment by kitenetter** [comment] 2019-07-16 20:26
And just as I typed the previous comment the egg-timer got to the end! For user "Dipper" the problem as described at the start of this thread is visible on the dev site - there are no records under Explore - My records, and the account's preferred recording location has the full stop.

**Comment by burkmarr** [comment] 2019-08-16 14:29
@kitenetter I had a chance to look at this on iRecord Dev today. I wondered if the two users might have been pointing to a location which was subsequently deleted. I checked the Drupal DB and they were both pointing to location id 693. When I looked at the Warehouse website, this turned out to be VC Cheshire. When I looked in the drop-down locations list on their iRecord account pages, Cheshire was not in the drop-down list.

I wondered if this was a similar problem to the recent missing Eire problem so I checked Cheshire on the Warehouse website but the checkbox for 'all websites' was checked. However I double checked the Warehouse DB and there was a record against Cheshire in the locations_websites table. I unchecked the 'all websites' box in the Warehouse website and saved it again - the record in the locations_websites table in the Warehouse DB disappeared (in my haste I didn't check to see what website it had been linked to).

Going back to the iRecord account page, Cheshire was now in the drop-down list. However selecting it still set the location (in view mode) to a dot. This was resolved by clearing the cache.

Cheshire is in the drop-down list on the live site now (though I think we can assume that it wasn't at the time this problem was evident - just before the dev site was 'cloned' from it).

If the problem occurs again, the first thing to do is check what location the user is pointing to in the Drupal DB and then see if there are any problems on the Warehouse. I closing this now unless you can think of a reason to keep it open (in which case reopen it).

**Closed by burkmarr** 2019-08-16 14:29 UTC
Labels: bug
