### ISSUE TITLE
Importer V2: the 'Save matches...' checkbox is showing a duff graphic

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1760] opened 2024-11-05 16:29 UTC
The 'Save matches... ' checkbox on the Value matching page seems to be showing a graphic image not found icon, possibly trying to show a tick or 'x' symbol:
![image](https://github.com/user-attachments/assets/44b720c3-3ad9-4ba7-b8c9-3730d5b84744)

Using FF.

**Comment by johnvanbreda** [comment] 2024-11-06 18:45
I couldn't reproduce this - there may have been a temporary failure on the connection to the server that hosts the icons. Plus we are dropping this icon in the next release anyway so will close this issue.

**Closed as completed by johnvanbreda** 2024-11-06 18:45 UTC
