### ISSUE TITLE
Verify (classic page) not updating today

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#535] opened 2019-04-01 15:22 UTC
Verify seems to be on a go-slow.
The initial page and the first page of applying a filter work fine but paging to '2' or 'Next', for example, fails with a SQL timeout error, even within a small grid of 80 rows.
We need the classic version of Verify to continue working, at least until more features are in the Elastic Search version.

**Comment by DavidHepper** [comment] 2019-04-03 13:01
Email from one of my verifiers today: "Is there a problem with iRecord today, its so slow as to be virtually unusable!"
This is getting embarrassing. I've not even received acknowledgement of the original report on 01/04.

**Comment by kitenetter** [comment] 2019-04-03 14:00
@DavidHepper do you mean acknowledgement of this github issue? We don't normally acknowledge issues individually, but they are read. (If you mean an email then apologies if we haven't got back to you yet.)

The performance issues are a continuing concern, and at the moment I can only say that we are continuing to work on them. In the meantime the new verification page offers a faster alternative, and personally I find it works well even though it is lacking some of the functionality of the old page.

**Comment by DavidHepper** [comment] 2019-04-03 14:32
I can't force your the priorities but I believe the primary function of iRecord is to collect, verify and store. Of these the most interactive is verify so verifiers suffer the most from slow-downs, timeouts and hangs. Having spent considerable time explaining and documenting how **Review grid** and **Review tick-list**, for example, can speed up operations for my verifiers it is galling to be advised to use an alternative page that doesn't have those facilities, while the original page that does have them is away with the faeries. It's even tempting to speculate that the Elastic Search indexer might be _causing_ the performance issues, unless proven otherwise. We really are frustrated. This issue has been going on, to a greater or lesser extent, for exactly a month, since iRecord repeatedly went offline (as polled by my monitor) in broad daylight between the 5th and 9th of March.

**Comment by johnvanbreda** [comment] 2019-04-04 08:09
@DavidHepper I can assure you that this remains an area of top priority. The difficulty I am having is that as usage grows, we keep encountering new areas that need work. The performance issues of about a month ago were a completely different issue to those which occurred yesterday for example.

One thing I have monitored carefully is to ensure the polling of records from the new Elasticsearch service does not have a significant negative impact and I can confirm that it doesn't. During yesterday's slowdown, it was using approx 8 seconds of CPU time (1 of 4 cores) every 2 minutes. Under normal service it uses much less than this - 8 seconds was only required because it is competing with other processes when under load.

The new facility does have a version of the Review Tick List tool - under the icon on the top left of the grid. 

@kitenetter it would be useful if you could collate a prioritised list of the missing features that are needed on the new tool so I can focus any efforts effectively. E.g. I am unsure if the review grid feature is now the next top priority given that there is a ticklist tool.

**Comment by kitenetter** [comment] 2019-04-15 20:55
Missing features now prioritised. Old page is functioning so far as I'm aware. Closing.

**Closed by kitenetter** 2019-04-15 20:55 UTC
