### ISSUE TITLE
iRecord unavailable

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1439] opened 2023-03-18 11:40 UTC
I am unable to view records on iRecord this morning; error messages say server/service unavailable. First noticed at about 10am.

**Comment by kitenetter** [comment] 2023-03-18 11:42
It's possible to see records on the old Explore pages, so this must be an Elastic Search issue.

**Comment by kitenetter** [comment] 2023-03-18 12:11
Apparently it went offline some time on Friday evening.

**Comment by johnvanbreda** [comment] 2023-03-18 16:20
I've restarted the Elasticsearch service which had stopped.

**Comment by kitenetter** [comment] 2023-03-18 17:37
Thanks @johnvanbreda - closing.

**Comment by kitenetter** [comment] 2023-03-19 11:36
We seem to have lost connection to ES again.

**Comment by johnvanbreda** [comment] 2023-03-19 14:42
Fixed again. It went down twice today.
@BirenRathod both times, the crash was caused by a lack of Java Heap Space. It was set to 2Gb but can be much higher than this according to the ES documentation. I've set it to 8gb but looking at the docs it might be worth going up to 20gb or thereabouts given the server available RAM now.

**Comment by BirenRathod** [comment] 2023-03-20 08:59
@johnvanbreda Thanks for increasing JAVA heap. yes, it required to increase. I think, it should increase up to 16 or 24 GB possibly.

**Comment by BirenRathod** [comment] 2023-03-20 09:51
@johnvanbreda In fact that is what I did last when it had been shut down about two weeks ago. See the below screenshot.
![image](https://user-images.githubusercontent.com/5941255/226304480-7666f64a-11f2-472d-8417-a1bdec6cad11.png)

**Comment by johnvanbreda** [comment] 2023-03-20 09:55
I'm not sure which is the best way to make this change - I altered it using jvm.options but maybe that hasn't worked either then. The error in the log indicated it ran out of heap space at 2gb.

**Comment by BirenRathod** [comment] 2023-03-20 09:57
@johnvanbreda Actually both didn't work, so I'm figuring out the actual cause of it.

**Comment by johnvanbreda** [comment] 2023-04-27 12:43
Closing as original issue sorted.

**Closed by johnvanbreda** 2023-04-27 12:43 UTC
Labels: maintenance
