### ISSUE TITLE
user login problem

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#352] opened 2018-03-22 08:54 UTC
User registered on iRecord (user name pete stroh) cannot reset password.  I believe Pete first setup an Indicia account via the NPMS, then used the iRecord app and now wants to login to the main iRecord website.  I suspect the website-user links need reviewing.

**Comment by BirenRathod** [comment] 2018-03-22 09:13
I and Andy had spent little time to investigate on this issue. Look my comments here https://github.com/BiologicalRecordsCentre/iRecord/issues/307

It is pending to be resolved by @johnvanbreda.

**Comment by andrewvanbreda** [comment] 2018-03-22 10:16
The users should be prompted which websites they are already a member of, does the error occur if this is filled in first? Or is the error occurring as the user attempts to fill this in?
If this linking bit is filled in OK, the website should work ok after that

**Comment by andrewvanbreda** [comment] 2018-03-22 10:16
See here
![linking screen](https://user-images.githubusercontent.com/2463614/37764604-08a8e90c-2dba-11e8-9eb1-4ffc9cbab33e.jpeg)

**Comment by andrewvanbreda** [comment] 2018-03-22 10:17
See here
![linking screen](https://user-images.githubusercontent.com/2463614/37764688-3b69defa-2dba-11e8-9378-f44ea9407de8.png)

**Comment by andrewvanbreda** [comment] 2018-03-22 10:18
![linking screen](https://user-images.githubusercontent.com/2463614/37764722-4cd9c8c6-2dba-11e8-811e-9a88d27ef9ba.png)

**Comment by andrewvanbreda** [comment] 2018-03-22 11:30
@johnvanbreda 

I have experimented on my machine, I cannot reproduce the problem (note I am probably running newer code). I don't think it should even be asking you that question about linking in that situation as the person's name and email is the same.

However I remember there was something really really strange about Pete's account a few month's back. I think the problem might be limited to him.
I was working with Biren on it, it was really odd. Something like his user ID matched the person ID of another user with a different name who has the same email address as him. It was really very odd.
I will speak to Biren about it.

John, I wouldn't do anything on this until I get a chance speak to Biren unless you know what is wrong straight off the top of your head.

**Comment by johnvanbreda** [comment] 2018-03-22 13:30
@BirenRathod The problem was that when you deleted user ID 86228, you left behind an old record in the user_identifiers table which then linked Pete's email address to the wrong user. So the system was genuinely confused and right to ask the question!
I've fixed it with the following SQL:
`update user_identifiers set user_id=68129 where identifier like 'peter.stroh%'`

**Closed by johnvanbreda** 2018-03-22 13:30 UTC
Labels: Urgent

**Comment by BirenRathod** [comment] 2018-03-22 14:09
It was @andrewvanbreda's decision to delete the user as he checked all the records. So seems like he was not aware of that too.

Anyway, it has resolved now. Many thanks.
