### ISSUE TITLE
Importer v2: stuck at the moment?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1625] opened 2024-01-30 09:55 UTC
This morning I'm getting stuck on the "Import settings" page: the background processing never completes:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/16039111/6632cbf9-51b5-4813-a379-7cd80ce98af6)

Will check again later to see if this problem persists.

**Comment by kitenetter** [comment] 2024-01-30 13:44
Still stuck this afternoon, but it seems to be a problem with the particular spreadsheet I was trying to import. I copied the data (just one record) and pasted it into a new, clean spreadsheet and this time it has imported with no problems. Not sure why the first spreadsheet got stuck, but closing for now.

**Comment by johnvanbreda** [comment] 2024-01-30 13:46
@kitenetter if something similar happens in future - please can you check if the more info... link gives more details. Also check the Drupal logs or provide a time that the problem occurred so I can check both Drupal and warehouse logs. Finally, it's always worth checking the Console tab on the developer tools if a page gets stuck like this.

**Comment by kitenetter** [comment] 2024-01-30 13:55
@johnvanbreda I just tried the original file again, at 13:50-13:51. More info produces this:
`More info...
Uploading the file to the server.
File uploaded to the server.
Preparing to load records.
Loading records into temporary processing area.
Loading records into temporary processing area. (33%)
Loading records into temporary processing area. (33%)
Loading records into temporary processing area. (33%)
Loading records into temporary processing area. (33%)
...`

followed by an apparently infinite repetition of the "Loading records" line.

The only information I can see in the console is a sequence of eight repetitions of:
`js_vX4MYg4TAPEq9FHTHmMjAgKGvNz61UWytx-DYTrKhQI.js?scope=footer&delta=0&language=en&theme=irecord&include=eJyNk9FuwyAMRX8oDVK3lz3uS5ADTspKMLJN1_z9SERWrdraPYEvx_aV44D3SpAWA-3Sj0xJO0eReKCr8ThCiTfBhhRDQnMX1_ekeNUC0XguGWJ_Uw6VOEs3EU0RLSSIiwYn5l7owkg8mwEE21VPOGM_EKkoQz68NL3kSOCRWzjWVhY-UWjeM0dIbqn-WpjIo307vh47WUSxNXHEuNsFp-GCm9UOi3VE54D1mHMMtRaa30S7j-fbosmU6VKd3RQlihryTbGiS0QxOZYppH4Ad56YSvJ2m2o_lBD9n_g61P-DEMOUZkz6BM51AUKanlAz8Ob4ITQQ10_zBBLHFKPFcUSn0uBTECVeTG1zPoAcGMH_-Eg-QKSphw-4dutYB2DTzq4I8s6t9z7UDZSKlZUp_HhF9yrg55Bsi7ZT9g5bwU5OxOqK7jX2-Gfmd44y4oOn_rQuS6g26k93D6A4yPi-Jn8B88dwZw:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Comment by kitenetter** [comment] 2024-02-04 23:21
Just had another spreadsheet upload get stuck in an apparently endless "Loading records into temporary processing area" loop. At approx. 23:18 on 4 Feb 2024.

The console messages are:
`Accessibility
Buttons must have discernible text: Element has no title attribute
Elements must only use allowed ARIA attributes: ARIA attribute is not allowed: aria-expanded="true"
Compatibility
'content-type' header charset value should be 'utf-8'.
Performance
A 'cache-control' header contains directives which are not recommended: 'must-revalidate'
Security
The 'Expires' header should not be used, 'Cache-Control' should be preferred.
The 'X-Frame-Options' header should not be used. A similar effect, with more consistent support and stronger checks, can be achieved with the 'Content-Security-Policy' header and 'frame-ancestors' directive.`

**Comment by kitenetter** [comment] 2024-02-04 23:27
I saved my Excel file as a csv and then re-saved as .xlsx and it then imported with no difficulty.

**Comment by johnvanbreda** [comment] 2024-02-05 14:21
@kitenetter please can you send me one of your failing CSV files.

**Comment by johnvanbreda** [comment] 2024-02-13 10:58
This is probably a duplicate of #1632 so will close, but please re-open if you can reproduce still.

**Closed as completed by johnvanbreda** 2024-02-13 10:58 UTC
Labels: bug
