### ISSUE TITLE
Non-Research Grade iNaturalist Records on iRecord

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1326] opened 2022-07-22 15:32 UTC
A verifier has identified some records that are on iNaturalist as "Needs ID", but have made it to the iNaturalist verification page on iRecord. They gave these examples, I've added the iRecord IDs that I have found so far to match:

https://www.inaturalist.org/observations/120141079 - iRecord ID 25893518
https://www.inaturalist.org/observations/120142541 - iRecord ID 25893519
https://www.inaturalist.org/observations/120143072
https://www.inaturalist.org/observations/120147494 - iRecord ID 25893526
https://www.inaturalist.org/observations/120315140
https://www.inaturalist.org/observations/120141162 - iRecord ID 25925855

**Comment by johnvanbreda** [comment] 2022-07-26 09:07
@robin-hutchinson I really don't know how this happened - the code at our end for applying the research_grade parameter is quite simple and unlikely to suddenly not work. It does seem like a batch of the iNat data came through without the research_grade filter. If our filter system had failed, you might have expected to get records from all over the world since the place filter is applied in exactly the same way. Is it possible that there was a temporary glitch in the iNat API? The only other possibility is one of us temporarily editing a file on the warehouse - I have recently worked on the BTO sync config so I guess it's a possibility I broke something, but I don't recall touching the iNat config.

**Comment by robin-hutchinson** [comment] 2022-07-26 09:19
That is interesting - I've had a look at the iNaturalist API github (https://github.com/inaturalist/iNaturalistAPI/issues?page=1&q=is%3Aissue) and cant find anything to indicate a bug in their system, I can add a new issue for them?

**Comment by johnvanbreda** [comment] 2022-07-26 09:25
I don't think it's worth doing that unless we manage to reproduce the issue, especially as we don't really know which end the problem originated at, and also as it doesn't seem to be a problem now.

**Comment by robin-hutchinson** [comment] 2022-07-26 09:27
Good point - is there a way for us to remove these records so they are not seen by verifiers? I'm not sure whether other records were affected as I've only heard from one verifier.

**Comment by johnvanbreda** [comment] 2022-07-26 09:52
I guess we could write a custom PHP script (or some other language) which gets all the UK research grade data again, so we can compare the IDs with our dataset. It would be a bit of effort though.

**Comment by kitenetter** [comment] 2022-07-26 10:17
Since this appears to be a one-off problem I don't think we should spend a lot of time on custom scripts. @robin-hutchinson please can you reply to the original enquirer to say that we've investigated and can't find an ongoing problem, and ask them to let us know if they see anything similar happening again?

Closing for now, but we can re-open if further examples come to light.

**Closed by kitenetter** 2022-07-26 10:17 UTC

**Comment by robin-hutchinson** [comment] 2022-07-26 10:54
Of course, I will let them know!
