### ISSUE TITLE
Output grid ref for Channel Islands gives lat/long

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#218] opened 2017-06-01 21:48 UTC
Records located using projection UTM30ED50 in the Channel Islands provide a grid reference in the "Grid ref" download column, and lat/long coords in the lat/long download columns, but the "Output grid ref" column displays lat/long coords. It would be more helpful if the "Output grid ref" always contained the grid ref, not any lat/longs.

**Comment by johnvanbreda** [comment] 2017-08-01 08:30
Duplicate of #243

**Closed by johnvanbreda** 2017-08-01 08:30 UTC
Labels: bug
