### ISSUE TITLE
Updates requested for RSPB boundaries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#797] opened 2020-02-19 09:29 UTC
RSPB have asked:
"could we update the RSPB reserves held on iRecord with latest version which is available from here: https://opendata-rspb.opendata.arcgis.com/datasets/rspb-reserves/data?orderBy=Name

"There have been a few boundary changes, and one or two new reserves, most recently Loch Druidibeag on South Uist."

@burkmarr are you likely to have time to do this soon or do we need to schedule it in for later in the year (RSPB would like it as soon as possible of course!).

**Comment by burkmarr** [comment] 2020-02-19 13:47
@kitenetter - I will look at it after the SSSI is done if that's okay.

**Comment by burkmarr** [comment] 2020-02-27 10:07
@kitenetter - I've done some preparatory work on this and will probably proceed with it before the SSSI load since that is a very big job which is currently stuck because of some problems on dev where I want to test it.

Checking the RSPB reserve locations already on Indica highlighted a few problems wich are worth documenting. The "Baron's Haugh" reserve is one of a number of RSPB reserves which are duplicated on Indicia. In this case the existing reserves have these names:

- Baron's Haugh
- BARONS HAUGH

The duplication is likely to have resulted from a previous update because the names aren't exactly the same. The location shapefile updload matches the names to see which location boundaries should be replaced and if it doesn't find a match it creates a new location. In the new shapefile from RSPB, the name of this reserve is 'BARON'S HAUGH' which matches neither of the two in there already and would result in a third location for the reserve if no preparatory work was done. It underlines the importance of doing a name comparison before running a boundary update.

In theory, if there are no boundary changes on a particular reserve then can be removed from shapefile to be used in the update. But in this case I used GIS to compare the geometry and there seem to be minor changes on practically all the reserves. This may be due to changes in the way the data are managed or represented on the RSPB side. Whatever the source of the differences, we should update all the current boundaries to match.

Here are the changes I've identified and the action I will take, where necessary, before the update.

- Baron's Haugh a duplicate of BARONS HAUGH and becomes BARON'S HAUGH. Delete one of the existing sites and rename another to BARON'S HAUGH.
- LOCH GRUINART & ARDNAVE is duplicate of LOCH GRUINART. Delete LOCH GRUINART & ARDNAVE (the name in the new shapefile is LOCH GRUINART).
- MALLTRAETH MARSH is a duplicate of CORS DDYGA. Delete MALLTRAETH MARSH (the name in the new shapefile is CORS DDYGA).
- READS ISLAND a duplicate of READ'S ISLAND. Delete READS ISLAND (the name in the new shapefile is READ'S ISLAND).
- THE REEF, TIREE is a duplicate of THE REEF. Delete THE REEF, TIREE (the name in the new shapefile is THE REEF).
- COOMBES & CHURNET VALLEYS becomes COOMBES VALLEY AND CONSALL WOODS. Update name of existing to match the new name.
- FEN DRAYTON becomes FEN DRAYTON LAKES. Update name of existing to match the new name.
- HESKETH OUT MARSH becomes OUT MARSH, RIBBLE ESTUARY. Update name of existing to match the new name.
- LABRADOR BAY now split into LABRADOR BAY and ASHILL. No action required.
- AIRBURN INGS now split into FAIRBURN INGS and ST AIDAN'S. No action required.
- WINTERBOURNE DOWNS now split into WINTERBOURNE DOWNS and SUDDERN HILL. No action required.
- SHERWOOD FOREST is a new reserve. No action required.
- LOCH DRUIDIBEG is a new reserve. No action required.

**Comment by kitenetter** [comment] 2020-02-27 10:13
Thanks @burkmarr. That all looks fine to me, but do you think we should run the proposals past RSPB (WIll George) for approval? If so I can do that or I can give you Will's email if you don't already have it.

**Comment by burkmarr** [comment] 2020-02-27 10:17
@kitenetter - I don't think there's any need since we are just bringing everything on Indicia into line with https://opendata-rspb.opendata.arcgis.com/datasets/rspb-reserves/data?orderBy=Name. Presumably it was Will that pointed you to this shapefile?

**Comment by kitenetter** [comment] 2020-02-27 10:20
Yes, that's correct, so it should be fine.

**Comment by burkmarr** [comment] 2020-02-27 18:13
@kitenetter. The new boundaries are uploaded to Warehouse 1 and have been spatially indexed so this should be good to close now.

**Comment by kitenetter** [comment] 2020-02-28 09:52
Looks good, thanks. Closing.

**Comment by kitenetter** [comment] 2020-02-28 11:20
The records are visible on the old Explore pages when filtering with the new RSPB boundaries, but not on the elastic explore. Is that just a matter of time for the ES layer to update, or do we need to schedule something to update it?

**Comment by johnvanbreda** [comment] 2020-02-28 11:51
I'll need to add the RSPB boundaries to the ES lookup table and re-index.

**Comment by johnvanbreda** [comment] 2020-02-28 12:31
Re-index started....

**Comment by johnvanbreda** [comment] 2020-03-04 14:40
Seems OK now, closing.

**Closed by johnvanbreda** 2020-03-04 14:40 UTC
Labels: maintenance
