### ISSUE TITLE
Testing iRecord post-server migration

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1587] opened 2023-11-16 10:45 UTC
Testing and tick when OK:
- [x] Adding records (casual record & list, including with photo)
- [x] Verification (verify a record, add comment)
- [x] downloading records
- [x] my sites (creating and editing)
- [x] Activities (creating and displaying)
- [ ] setting up a new recording form
- [x] uploading from spreadsheets
- [x] Explore pages (my/all records, sites, species pages)
- [x] Forum pages and posting
- [ ] check for PHP errors
- [ ] check the apps work
- [x] help pages viewing correctly

Issues arising and tick when resolved:
- [x] Verification (send email) - says sent OK but not appearing in recipient inbox (perhaps just delay?)
- [x] Recorder league tables stuck computing
- [x] Various reports of delays on the site including 'application did not respond in time' when list of records added, although they did in fact save
- [x] Records taking ages to save, then appearing multiple times under different record numbers

**Comment by kitenetter** [comment] 2023-11-16 11:34
I'm logged in as iRecord support. When I go to "Explore - My records", I can see a lot of records from the RHS Honey Fungus Hunt survey (survey ID 477). In the warehouse these records are flagged as "Record is part of a project that has not yet released its records".

They were not visible under "Explore - My records" on the old site, but they are now. Under "Explore - All records" they are not visible on the new site, which is how it should be.

So this isn't a major problem, but I wonder if it is an indication that the "not yet released" flag is being handled incorrectly.

**Comment by kitenetter** [comment] 2023-11-16 15:02
@Sam-Amy I would expect you to be able to see all your records on the old version of the My records page, and just some of them on the elastic version of that page (until it catches up). Are you seeing something different?

**Comment by Sam-Amy** [comment] 2023-11-16 15:03
No, that is what I'm seeing - as expected I now realise!

**Comment by johnvanbreda** [comment] 2023-11-17 10:29
@Sam-Amy I have fixed the league table, which were using out-of-date Elasticsearch configuration. I also fixed the species sort version, but note that text explaining that the sort will only change the order of the top 100 rows ("Although you can sort on the record count field, this will still be the top 100 recorders by species count.") is actually incorrect - the column sorts will now do an accurate sort across the entire dataset. So this text can be removed and possibly the species sort version of the page is no longer necessary so can be deleted.

**Comment by kitenetter** [comment] 2023-11-17 10:52
I think this might have been raised already via email: there are a very large number "Undelivered Mail Returned to Sender" messages in the iRecord inbox this morning.

And I know that Sam tried to send me a query message yesterday from the verification page, but it hasn't arrived.

**Comment by kitenetter** [comment] 2023-11-17 22:51
On the verification page, the "Additional occurrence attributes" panel is often painfully slow to load up, and doesn't always refresh quickly when moving from one record to another.

**Comment by kitenetter** [comment] 2023-11-20 08:52
I haven't received any email notifications since the server move.

**Comment by johnvanbreda** [comment] 2023-11-20 09:20
@BirenRathod would you be able to look into the emails please? Presumably it is requiring configuration on the warehouse.

@kitenetter I've not been able to reproduce problems with the additional attributes being slow to load - is it still slow for you?

**Comment by BirenRathod** [comment] 2023-11-20 09:25
@johnvanbreda I emailed to our IT team to look into the email. The configuration is already done.

**Comment by Sam-Amy** [comment] 2023-11-20 09:25
@kitenetter re: additional occurence attributes, do you mean when you add more grid column settings? If so no delay there for me either.

**Comment by Sam-Amy** [comment] 2023-11-20 09:29
@BirenRathod & @johnvanbreda I don't know if the fact that we are still getting tonnes (~700+ over the weekend) of these underlivered mail returned emails to the irecrod inbox is relevant? For reference; I asked IT about this last week and they said "these are related to emails your system has attempted to save and the 3rd party mail filtering is not limiting you as such your getting bounce backs", and Biren replied with "I got from Simon Courtney when he checked a few months back that the email server has got only 500 limit to send emails in one day. If that limit is exceeded then the server fails to deliver the emails" - don't know if you heard back Biren?

**Comment by BirenRathod** [comment] 2023-11-20 09:35
@Sam-Amy No I haven't but I will chase them again.

**Comment by BirenRathod** [comment] 2023-11-20 10:52
This is what I got from the IT team back in September.
Hello Biren,

There is a limit on outgoing emails on wlla from a single host. This is set at 500. See error report that just came in:-

:----------------------------------------------:
The number of emails sent by one or more hosts has exceeded the threshold (500).
The following shows the number of emails assigned to each hostname above the threshold.
Generated by script /packages/local/bin/number-email-check
5891 CEHWLBRCWEB2
:----------------------------------------------:

Kind Regards,
Simon Courtney

**Comment by Sam-Amy** [comment] 2023-11-20 10:57
We've just had a report re: irecrod and NMRS websites that certain photographs are assigned the wrong licence attribution:
"I have noted that certain photographs are assigned the wrong licence attribution and this appears to be random. I have not assigned any specific licence to my photos. Some show 'CC BY-NC-SA' which is incorrect."

I am awaiting a specific example. 

This user also noted that frequently it is impossible to navigate around the websites which is extremely frustrating!

@johnvanbreda @kitenetter @JimBacon @burkmarr  would it be better to raise these things now as seperate issues?

**Comment by kitenetter** [comment] 2023-11-20 11:15
@johnvanbreda re the "additional occurrence attributes" it seems to be an issue on the photo verification page, but not on the standard verification page. If I go to the photo verification page and open up an individual photo card, the additional occurrence attributes often get populated quickly, but every so often I go to the next record and I get a egg-timer for ages waiting for the additional occurrence attributes to fill in. I just tried again and I've got an elasticsearch query failed message, and the additional occurrence attributes have not populated at all.

@Sam-Amy this refers to the section of additional occurrence attributes that is shown in the Details box on the right of the verification page.

@Sam-Amy lets keep the issues relating to notifications and general performance in this thread, but I think it would be better to set up new issues for other things, so please can you transfer the photo licence one into a new issue.

**Comment by kitenetter** [comment] 2023-11-20 11:16
@BirenRathod 500 emails a day is not going to be enough. Can we ask for this limit to be increased?

**Comment by BirenRathod** [comment] 2023-11-20 11:48
> @BirenRathod 500 emails a day is not going to be enough. Can we ask for this limit to be increased?

Yes, I know and I already asked to IT.

**Comment by BirenRathod** [comment] 2023-11-20 11:59
@kitenetter, @Sam-Amy & @johnvanbreda I send you an email which I received from IT.

**Comment by Sam-Amy** [comment] 2023-11-20 16:51
User ID 106783 has reported having problems with records taking ages to save, then appearing multiple times under different record numbers later on.  He tried deleting the duplicates, but that never seemed to work as the system kept hanging, so he has left them on at the moment and will try and remember to delete later.

**Comment by johnvanbreda** [comment] 2023-11-20 20:19
As a result of a lot of investigation today, Damien has altered the allowed number of PHP workers which may have improved things - I navigated both the warehouse and iRecord just now without problems. Let me know if similar issues occur again though.

**Comment by kitenetter** [comment] 2023-11-21 11:03
So far so good, I haven't had a timeout or an elastic error today, and I can no longer reproduce the problem with the additional occurrence attributes on the photo verification page

**Comment by BirenRathod** [comment] 2023-11-22 10:08
@kitenetter, @johnvanbreda is there a big implication if we ask IT to remove those backlog of emails? My understanding is that delivering those emails will take ages. eventually, they might remove those backlogs if they want to migrate to M365. 
Let me know your thoughts. 
I already asked IT for more options.

**Comment by johnvanbreda** [comment] 2023-11-22 10:11
@BirenRathod I gave IT a particular email address of a user account that had incorrectly set up alerts on every single record added to iRecord. If the backlog for just that email address can be deleted but leaving the others, then it would be good to know what the remaining backlog is before making a decision.

**Comment by BirenRathod** [comment] 2023-11-22 10:21
@johnvanbreda When they checked the number yesterday, it was 10000+ emails in the backlog.

**Comment by johnvanbreda** [comment] 2023-11-22 10:24
For that one email address? I'm not surprised though. Can the emails for that address only be deleted from the backlog and if so, how many are left?

**Comment by BirenRathod** [comment] 2023-11-22 10:31
@johnvanbreda do you think that all 10000+ using the same email address? IT is checking at present.

**Comment by BirenRathod** [comment] 2023-11-22 11:03
@kitenetter  & @Sam-Amy The IT has just confirmed that the queue has almost cleared, so that means you can test the emails form iRecord.

**Comment by kitenetter** [comment] 2023-11-22 16:06
I've just received my first notification email since before the move!  :) :)

**Comment by BirenRathod** [comment] 2023-11-22 16:10
@kitenetter IT has just confirmed that UKRI who looks after the email system has increased the limit from 500 to 1800 per hour which should help to clear the backlog. So that should have resolved this problem.

**Comment by Sam-Amy** [comment] 2023-11-27 09:59
> 

@johnvanbreda @kitenetter can I just check please that this means that all records can now be sorted by both recorder OR species on the same page, and so we can delete the page https://irecord.org.uk/recorder-league-sp entirely and change the text on the https://irecord.org.uk/recorder-league to "This table shows the top 100 recorders as measured by record count (default) or species count". Thanks

Someone noted that the table by record numbers looks correct, but the table by species numbers shows a whole other set of results for the same people. I didn't notice this and now I am unable to access the page ('server busy') but if the above is correct then presumably doesn't matter anyhow?

**Comment by kitenetter** [comment] 2023-12-05 16:47
@johnvanbreda I agree with @Sam-Amy that if we can get the main page working fully, then we can unpublish https://irecord.org.uk/recorder-league-sp

However, at the moment if I go here https://irecord.org.uk/recorder-league and try to sort by species I'm getting "Elasticsearch query failed".

Also, when you click on the sort button it would be nice if it could sort in reverse order by default, rather than having to sort the column twice.

@Sam-Amy for User ID 73766 the league table appears to show the right number of records now, but may still be about 200 short for the species total, is that what you thought? It's possible that the league table is treating higher taxa differently to the My records table, but it seems surprising to be as many as 200 taxa missing.

**Comment by JimBacon** [comment] 2023-12-05 16:52
Do you want to just try that sort by species again?
I happened to restart the ElasticSearch service a minute or two before you posted.

**Comment by Sam-Amy** [comment] 2023-12-05 16:55
I'm also getting elasticsearch failed when trying to sort by species (but number of records sorts OK) on the recorder league table page https://irecord.org.uk/recorder-league

**Comment by JimBacon** [comment] 2023-12-05 16:59
So am I now. Worked 5 minutes ago. Will look for more details of the error.

**Comment by JimBacon** [comment] 2023-12-05 19:53
Got it.
This is interesting as I have seen a number of similar errors in the log but this is the first time I have known where it is coming from.
I don't understand anything more at the moment than something about the query is using a lot of memory.

```
19:30:02 error ES proxy request failed: : ""
19:30:02 error URL: http://192.171.199.248:9200/occurrence_irecord_report/_search
19:30:02 error Query: {
  "size":"0","aggs":{
    "_idfield":{
      "terms":{
        "size":"100",
        "field":"event.recorded_by.keyword",
        "order":{"species_count":"asc"}
      },
      "aggs":{
        "fieldlist":{
          "top_hits":{
            "size":"1",
            "_source":{"includes":["event.recorded_by"]}
          }
        },
        "species_count":{
          "cardinality":{"field":"taxon.species_taxon_id"}
        }
      }
    }
  },
  "query":{
    "bool":{
      "must":[
        {"term":{"metadata.trial":false}},
        {"term":{"metadata.confidential":false}},
        {"term":{"metadata.release_status":"R"}}
      ]
    }
  },
  "track_total_hits":true
}
19:30:02 error Response: {
  "error":{
    "root_cause":[
      {
        "type":"circuit_breaking_exception",
        "reason":"[parent] Data too large, data for [] would be [16353591368/15.2gb], which is larger than the limit of [15986170265/14.8gb], real usage: [16353591296/15.2gb], new bytes reserved: [72/72b], usages [request=9799281792/9.1gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=11586/11.3kb]",
        "bytes_wanted":16353591368,
        "bytes_limit":15986170265,
        "durability":"TRANSIENT"
      },
      {
        "type":"circuit_breaking_exception",
        "reason":"[parent] Data too large, data for [] would be [16781413568/15.6gb], which is larger than the limit of [15986170265/14.8gb], real usage: [16781410304/15.6gb], new bytes reserved: [3264/3.1kb], usages [request=9799281792/9.1gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=11586/11.3kb]",
        "bytes_wanted":16781413568,
        "bytes_limit":15986170265,
        "durability":"TRANSIENT"
      },
      {
        "type":"circuit_breaking_exception",
        "reason":"[parent] Data too large, data for [] would be [15992885640/14.8gb], which is larger than the limit of [15986170265/14.8gb], real usage: [15992881152/14.8gb], new bytes reserved: [4488/4.3kb], usages [request=4815990432/4.4gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=904/904b]",
        "bytes_wanted":15992885640,
        "bytes_limit":15986170265,
        "durability":"TRANSIENT"
      }
    ],
    "type":"search_phase_execution_exception",
    "reason":"",
    "phase":"fetch",
    "grouped":true,
    "failed_shards":[
      {
        "shard":1,
        "index":"occurrence_brc1_v1",
        "node":"jfYZPqItRoerXINWPj3lNw",
        "reason":{
          "type":"circuit_breaking_exception",
          "reason":"[parent] Data too large, data for [] would be [16353591368/15.2gb], which is larger than the limit of [15986170265/14.8gb], real usage: [16353591296/15.2gb], new bytes reserved: [72/72b], usages [request=9799281792/9.1gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=11586/11.3kb]",
          "bytes_wanted":16353591368,
          "bytes_limit":15986170265,
          "durability":"TRANSIENT"
        }
      },
      {
        "shard":2,
        "index":"occurrence_brc1_v1",
        "node":"jfYZPqItRoerXINWPj3lNw",
        "reason":{
          "type":"circuit_breaking_exception",
          "reason":"[parent] Data too large, data for [] would be [16781413568/15.6gb], which is larger than the limit of [15986170265/14.8gb], real usage: [16781410304/15.6gb], new bytes reserved: [3264/3.1kb], usages [request=9799281792/9.1gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=11586/11.3kb]",
          "bytes_wanted":16781413568,
          "bytes_limit":15986170265,
          "durability":"TRANSIENT"
        }
      },
      {
        "shard":3,
        "index":"occurrence_brc1_v1",
        "node":"jfYZPqItRoerXINWPj3lNw",
        "reason":{
          "type":"circuit_breaking_exception",
          "reason":"[parent] Data too large, data for [] would be [15992885640/14.8gb], which is larger than the limit of [15986170265/14.8gb], real usage: [15992881152/14.8gb], new bytes reserved: [4488/4.3kb], usages [request=4815990432/4.4gb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=904/904b]",
          "bytes_wanted":15992885640,
          "bytes_limit":15986170265,
          "durability":"TRANSIENT"
        }
      }
    ],
    "caused_by":{
      "type":"circuit_breaking_exception",
      "reason":"[parent] Data too large, data for [] would be [16039709328/14.9gb], which is larger than the limit of [15986170265/14.8gb], real usage: [16039668208/14.9gb], new bytes reserved: [41120/40.1kb], usages [request=41120/40.1kb, fielddata=3962171/3.7mb, eql_sequence=0/0b, model_inference=0/0b, inflight_requests=904/904b]",
      "bytes_wanted":16039709328,
      "bytes_limit":15986170265,
      "durability":"PERMANENT"
    }
  },
  "status":429
}
19:30:02 error ClientSystemId: BRC
19:30:02 error Rest API request failed: HTTP 500 Internal server error.
```

**Comment by JimBacon** [comment] 2023-12-14 16:22
The Elasticsearch error arising from sorting the recorder league by species count has been resolved by modifying the configuration of the form to include a sortAggregation option, see https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html#typical-configuration-examples. This reduces the amount of memory the query has to use.

**Comment by Sam-Amy** [comment] 2023-12-17 17:35
I've just noticed this warning on the Indicia warehouse, but I'm not sure what it means. Is it anything to be concerned about? Thanks.

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/104146164/54def965-2122-4882-ab0b-219925a20bef)

**Comment by JimBacon** [comment] 2023-12-18 09:25
That is expected and not a concern. Those folders need to be writeable for the initial application installation but, on the new infrastructure, they are then made read-only to reduce the possibility for unwanted change.

**Closed** 2023-12-18 09:32 UTC

**Comment by kitenetter** [comment] 2024-01-02 11:55
@Sam-Amy I have now unpublished https://irecord.org.uk/recorder-league-sp (but don't know why your permissions didn't allow you to do so).

The sort order is still a bit erratic (i.e. it does not list the numbers in a properly sorted order) but that seems to be a feature of all these ES aggregated totals.
