### ISSUE TITLE
Page navigation below the grid in Verify often shows incorrect links and totals

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#340] opened 2018-03-07 17:03 UTC
The navigation of the grid shows page links, including First, Previous, numbered pages, Next and Last. When records are retrieved this typically shows links to pages **1** (greyed-out because we are on it) and **2..6**, regardless of the number of records retrieved. 
The text e.g. "Showing records 1 to 6 of " is generally correct but the total is often the unfiltered total. This sometimes updates without warning after other things on the page.
In the example screenshot there are only 6 records in the grid, so only enough for one page, but the links to pages 2 to 6 are present and active, and lead to empty grid pages without navigation!
![image](https://user-images.githubusercontent.com/24915271/37105469-295b71e0-2227-11e8-876c-63b9e9ec841a.png) 
You should be able to reproduce it by masquerading as me and putting "*holliday*" into the **Recorder** column filter.
I'm reasonably sure that this is affecting everyone. It is disconcerting and if people do navigate to an empty grid page they cannot go back without losing the current filter.

**Comment by japonicus** [comment] 2018-03-07 17:22
related to #137 and #150

**Comment by johnvanbreda** [comment] 2018-03-08 20:35
Thanks @DavidHepper - this will be fixed next time I update the code.

**Comment by DavidHepper** [comment] 2018-06-27 10:55
This works better now but occasionally still shows nonsense such as "Showing records 31 to 60 of 40" e.g. when entering wr* in the Recorder column filter.
(Not tested fully.)

**Comment by johnvanbreda** [comment] 2018-06-29 09:53
Hi @DavidHepper I tried masquerading as you on both Windows (Chrome) and Mac (Safari) but could not reproduce this.

**Comment by DavidHepper** [comment] 2018-07-18 19:37
This still occurs in Verify even when relatively simple Filters are set. The latest example is:
- Masquerade as me (Filtering by What > Odonata is implicit)
- Filter by Where > VC > West Cornwall & Scilly
This currently shows 5 unreviewed records but the navigation controls are incorrect. See attached screen-shot > ![verify - grid navigator bar confusion 1](https://user-images.githubusercontent.com/24915271/42903561-2595e07a-8aca-11e8-9699-bb3c2a6f7860.jpg)

Note that on the second attempt/refresh with the same filters the totals are correct and the navigation controls are greyed out as expected.

**Comment by johnvanbreda** [comment] 2019-05-30 16:31
Closing - seems correct now.

**Closed by johnvanbreda** 2019-05-30 16:31 UTC
Labels: fixed in develop branch
