### ISSUE TITLE
iRecord importer issue - assigning records to 'admin' instead of user

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#634] opened 2019-07-23 08:27 UTC
We've had reports of when importing a csv file using 'survey = iRecord General data' and UK master list the records are assigned to 'admin' rather an a user's own account.

**Comment by kitenetter** [comment] 2019-07-24 08:35
One of the users affected is Derek Whiteley, warehouse user ID 8590. Derek would like the records to be linked back to his account rather than admin core, but I can't immediately see a way of finding the set of records in question, and I'm not sure how many other users might be affected.

Marking this as urgent since if it continues we will be faced with lots of requests to reassign records.

**Comment by DavidRoy** [comment] 2019-07-26 06:36
More reports of issues with the importer. https://www.brc.ac.uk/irecord/node/7802

**Comment by kitenetter** [comment] 2019-08-08 18:25
This is continuing to cause concern for users importing records.

**Comment by johnvanbreda** [comment] 2019-08-09 08:50
I'll look into this now...

**Comment by johnvanbreda** [comment] 2019-08-09 08:57
@kitenetter can you obtain details of some of the records in Derek's import? If I can find them then the import guid will help with reallocation.

Do you have any files that replicate the problems with habitat mapping from the forum post?

**Comment by DavidRoy** [comment] 2019-08-09 08:59
Latest extensive post on some of the issues:
https://www.brc.ac.uk/irecord/node/7816

**Comment by johnvanbreda** [comment] 2019-08-09 09:00
Thanks. It may be worth posting a holding reply for Rob so he knows we are looking into this right now?

**Comment by DavidRoy** [comment] 2019-08-09 09:01
have done....

**Comment by kitenetter** [comment] 2019-08-09 11:55
@johnvanbreda I've run a query to find samples where created_by_id = 1 (= admin core) and there are an alarmingly high number of them. About 1,000 are attributed to Derek Whiteley, and these are listed in the attached file. Suspect there may be quite a few others that have ended up in the wrong account.

[records_for_user_Whiteley.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/3486213/records_for_user_Whiteley.xlsx)

Let me know if you want me to try to identify other blocks of data that may need re-linking.

**Comment by DavidRoy** [comment] 2019-08-09 11:59
Anything with an import_guid and linked to an admin account this year?  Would be good to summarise these by recorder name?

**Comment by johnvanbreda** [comment] 2019-08-09 12:29
I've fixed the problem with the record not being linked to the user account and will take a look at the data now - if there is an obvious way to relink it I'll do it.

**Comment by johnvanbreda** [comment] 2019-08-09 14:18
I've now also fixed the problem with column mappings going out of sync. So any imports from now on should be OK.

**Comment by johnvanbreda** [comment] 2019-08-09 17:43
I've now fixed up the records imported by Derek Whiteley as well as 3 batches by Keith Porter. 

To find other imports which may have been caused by this problem:
```sql
select o.import_guid, string_agg(distinct s.recorders, '; ') as recorders, count(o.*) as records
from occurrences o 
join cache_samples_nonfunctional s on s.id=o.sample_id
where o.import_guid is not null and o.created_by_id=1 and o.website_id=23
and o.updated_on>'2019-06-25'
group by import_guid;
```

Once you've worked out the user_id to allocate to an import batch the following queries will reallocate the records:
```sql
update occurrences set created_by_id=<user_id> where import_guid in ('<import_guid>') and created_by_id=1; 
update cache_occurrences_functional set created_by_id=<user_id> where import_guid in ('<import_guid>') and created_by_id=1; 
```

**Comment by johnvanbreda** [comment] 2019-08-12 15:24
As this issue is fixed and I've updated the data to attach to the correct account where obvious, I'll close this but please re-open if there are cases where people need data re-allocated to their account.

**Comment by kitenetter** [comment] 2019-08-13 13:44
I can find 47 imports that need to be reassigned (although I'm waiting to get confirmation from four users before proceeding), and have tracked down the intended user accounts. I have the queries set up to to the updates, but that needs database editing permissions - can you take this on @burkmarr please?

Let me know if you want the info for ones that can be done now, or if you would prefer to wait until all are ready to go.

**Comment by burkmarr** [comment] 2019-08-14 07:40
Hi @kitenetter. Send me the ones that need doing now. I'm off next week so will do what I can before I go.

**Comment by kitenetter** [comment] 2019-08-14 08:44
@burkmarr have sent spreadsheet

**Comment by burkmarr** [comment] 2019-08-14 14:01
@kitenetter - all updates have been run except those in the first four rows as you specified. Let me know when you are ready for those to be run.

**Comment by kitenetter** [comment] 2019-08-14 14:11
Excellent, thanks @burkmarr

**Comment by kitenetter** [comment] 2019-09-25 18:35
@burkmarr I think we can now deal with the remaining four rows.

User Alan Smith (target id 230083) confirms that the records should be transferred as specified in the first two rows of the spreadsheet.

User Karl Horne confirms that the records need transferring, but to a different account than the one I specified in the 3rd and 4th rows of the spreadsheet. The target user id should be 190188 (**not** 163464).

Are you okay to edit the SQL accordingly and apply these last four updates?

**Comment by burkmarr** [comment] 2019-09-26 08:34
Okay those updates are done now @kitenetter.

**Closed by burkmarr** 2019-09-26 08:34 UTC
Labels: bug, maintenance, scale:small
