### ISSUE TITLE
Importer v2 - 'Undefined array key 2'

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1632] opened 2024-02-06 18:47 UTC
On uploading an Excel xlsx sheet containing a header row followed by one data row I get an error:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/a04bcff8-03a3-4836-bcc0-6b08e6b0178e)

The spreadsheet is a massaged export from another system. It contains data columns (in black or brown) and intermediate values not for direct import to iRecord (other colours).
[32. 2021-Beds - first row.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/14184829/32.2021-Beds.-.first.row.xlsx)

The full spreadsheet has 3,000 rows so I'm starting cautiously with Importer v2.
A similar sheet worked last year in the old importer.

**Comment by DavidHepper** [comment] 2024-02-06 18:54
Update: I've found a note from last time saying I had to convert it to CSV and remove the intermediate value columns even on the old importer, or it became confused. If you're too busy I can stick with this method.

**Comment by johnvanbreda** [comment] 2024-02-07 10:43
@DavidHepper I'll leave this one open, but not a top priority then as you have a workaround. If you do reproduce it again, would you be able to post a reasonably accurate time the error occurred so I can search the logs?

**Comment by johnvanbreda** [comment] 2024-02-08 12:23
@DavidHepper the underlying cause is that your 2 row spreadsheet is actually being saved as a 104K row spreadsheet by Excel, presumably because there is some formatting or other information in the blank rows that causes them to be included. It's the same problem as reported here: https://github.com/PHPOffice/PhpSpreadsheet/issues/1529. Although I can fix the error you encountered, note that the system will still try to scan the entire spreadsheet to find data rows and will therefore take a long time on this step.

**Comment by sacrevert** [comment] 2024-02-08 12:30
@johnvanbreda given that this is a very common issue with Excel (e.g. if one accidentally does something like Ctrl+END, or Ctrl+arrow key, Excel will scroll to the absolute max row/column allowable, and consider these rows/columns to be data, even though they have no entries or other formatting beyond the user indicating that they are somehow "part" of the file), I wonder whether the system could issue a warning about unnecessary blank row/column bloat?

**Comment by johnvanbreda** [comment] 2024-02-08 12:39
@sacrevert I was wondering the same. Or maybe just accept that if the importer discovers a largish block of empty rows, that data after the block will be skipped. If we set this limit to something like 100, the block will be discovered quickly, and it's very unlikely to be intentional. As long as the system tells you how many rows were found of course. Does that sound OK?

**Comment by sacrevert** [comment] 2024-02-08 12:41
I would have thought so. This happens to me all the time, but I suspect it's because I use a lot of keyboard shortcuts X D
Still, very easy to do in David's situation too, where one is "reusing" a sheet by deleting rows or columns

**Comment by DavidHepper** [comment] 2024-02-08 15:44
Hmm. I highlighted all rows of the block to be deleted and used **Ctrl+Num-** which I'd have thought is a fairly standard way to get rid of the whole lot. I think you'll have to handle this one in iRecord as it's bound to happen frequently. The 100 null rows test is good enough for me!
It isn't a problem when trimming down CSVs in the same way.

**Comment by johnvanbreda** [comment] 2024-02-13 10:35
Now fixed - if a block of 100 blank rows is found the importer will skip scanning the rest.

**Closed as completed by johnvanbreda** 2024-02-13 10:35 UTC
