### ISSUE TITLE
Output Map Ref is only a truncated Input map ref

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1017] opened 2021-02-18 15:54 UTC
While investigating dragonfly records from a trusted verifier that are unexpectedly mapped in the Atlantic Ocean, I've found a very odd case where the Output Map is apparently being miscalculated from input SW793338 to output SW79. The input ref is correct.

To find these, in ES Verify enter 'SW79' in the column header filter. I'm seeing 16 records, entered by Dave Cooper between Oct 2019 and Jun 2020.
It's hard to believe there is something magical about SW793338.
Might others, less easily detected because the Output map ref is on land, be truncated?

**Comment by kitenetter** [comment] 2021-03-24 15:27
The square shown on the map for the sample in the warehouse is SW79, even though the entered grid reference is SW793338. So this seems like a glitch during data entry rather than a problem with calculating the output map reference.

I think the records can be edited to 'correct' the grid ref (i.e. to refresh the grid ref so that the map shows the correct square).

But that leaves with the question of what went wrong during data entry.

Example record IDs:
13285689
12082369
14220341

The above were all entered by Dave Cooper and he was logged in at the time. Strangely, there are also a few records with the same grid ref problem that were entered by Dave Cooper when he wasn't logged in, e.g.:
13758937

On further investigation, Dave has a site "falmouth" in "My sites", and it looks like the grid ref confusion arises here:

![image](https://user-images.githubusercontent.com/16039111/112336868-5a7c5900-8cb5-11eb-9a98-006b7ad919cb.png)

@johnvanbreda is there any reason why I shouldn't edit Dave's "My sites" so that the map matches the more detailed grid ref?

**Comment by johnvanbreda** [comment] 2021-03-24 19:35
@kitenetter I suspect a glitch during editing of the site then. The data entry of the records just picked up the broken info from the site. It's difficult to know how it happened without information that might help to reproduce whatever went wrong when the site was edited.
Editing the site to fix the map square, as well as the records, should be an acceptable way to fix the data issue.

**Comment by kitenetter** [comment] 2021-03-24 20:41
Thanks - I've contacted Dave and will close this once we've got the site edited.

**Comment by kitenetter** [comment] 2021-03-25 16:10
"My sites" entry now corrected, and the individual occurrences relinked to that site. Closing.

**Closed by kitenetter** 2021-03-25 16:10 UTC
Labels: bug, question
