### ISSUE TITLE
Schedule of UKSI updates?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1617] opened 2024-01-22 15:59 UTC
I've made an update to UKSI via NHM and the change is showing in Sandbox where a new Preferred TVK is present. What is the schedule for updating iRecord, in sync with NBN Atlas, perhaps? If this won't happen by mid-Feb 2024 I'll have to revert to sending the old TVK.

Specifics:
_Anaciaeschna isoceles_ https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021009091 is becoming _Aeshna isoceles_ 
https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021689820 on this new TVK. (Don't ask!)

**Comment by Sam-Amy** [comment] 2024-04-10 13:00
I'm wondering if this is causing a similar issue I'm seeing with some byophyte taxa. @DavidHepper I can't see any records of Aeshna isoceles showing now on the explore page - did this get sorted for you?

**Comment by DavidHepper** [comment] 2024-04-10 18:05
It's complicated. I spoke with Chris Raper at NHM and he tells me that UKSI has to be pulled into iRecord (and other related systems at BRC) and separately into NBN Atlas. Although these 'pulls' are quite independent they ought really to be co-ordinated to keep consistency. The latest UKSI is in the Sandbox, for testing, but the one to be pulled is apparently an intermediate that can't be interrogated from the web, so it's all rather opaque to us mere mortals.
The NBN team is struggling to sort larger issues at present, so updating UKSI to the Atlas isn't high on their priorities. Currently _Aeshna isoceles_ still appears in both systems as _Anaciaeschna isoceles_.
Historically, updates to UKSI in iRecord have caused some issues that have to be sorted manually. For minor issues, my advice is to make doubly sure that the taxonomy in UKSI-Sandbox is squeaky clean rather than requesting custom fixed in iRecord. That way, when the updates eventually reach iRecord everything will work.

**Comment by DavidHepper** [comment] 2024-04-22 19:27
Do we have an ETA for update to the latest UKSI please, preferably in tandem with NBN Atlas taking it?

**Comment by johnvanbreda** [comment] 2024-06-13 09:50
@DavidHepper FYI iRecord's copy of UKSI was updated yesterday.

**Comment by DavidHepper** [comment] 2024-06-18 14:48
Thank you. Will this take a while to settle down? I'm seeing records of _Aeshna isoceles_ coming through, e.g. ID 36464674, but these don't have a Common Name. 'Norfolk Hawker' seems still to be attached to _Anaciaeschna_.
Also, while entering a new record, if I start entering 'Anaciaeshna is...' it shows 'NONE' after the Species name: 
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/24915271/64b8aafc-3852-4c74-bae1-98620fdb9b19)
and I'm still unable to see a Common Name when I enter the full, preferred species name 'Aeshna isoceles'.

**Comment by sacrevert** [comment] 2024-06-28 11:03
@johnvanbreda When you are back, can you explain something about the recent UKSI update. We had some changes to the UKSI made in April, including adding some common names for NPMS aggregates where they were lacking. (For example [Viola reichenbachiana/riviniana](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0020083544) (UKSI Sandbox link) had a common name added as [a synonym](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021762160). However, this does not show up as a common name where it appears on one of the NPMS species lists: [https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/368996 ](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/368996)

Could you explain what changes we need to make to either the UKSI, or in the warehouse, for such taxa to have a default common name in indicia? I have looked at taxa in the UKSI with common names that appear for data entry in iRecord and NPMS, but cannot spot any obvious difference in the information contained within entries (e.g. comparing Viola reichenbachiana/riviniana to Viola recihenbachiana). Thanks (tagging @andrewvanbreda and @Sam-Amy for info)

**Comment by DavidRoy** [comment] 2024-06-28 11:10
@burkmarr might also have some insights on this

**Comment by burkmarr** [comment] 2024-07-03 11:05
@johnvanbreda - I looked at the NPMS example and I found the operations to add the vernacular names mentioned by Oli in the UKSI CSV for the recent update. But when I looked at the results in the taxon table, I noticed that the scientific flag was set to true. Looking at the uksi_operations module, we always set the scientific flag to true when adding a synonym. (In fact we don't import the name_Type field from the UKSI CSV which indicates when a synonym is a vernacular name.) I changed that flag in the taxa table for the 'Common Dog-violet / Early Dog-violet' example and ran cache builder updates for taxa_taxon_list items which referenced 'Viola reichenbachiana/riviniana'. I thought that might update the default_common_name field in the cache_taxa_taxon_lists table, but it didn't. Can you throw any light on it.

(I'm also trying to work out what's happening in the case of Aeshna isosceles/Norfolk Hawker but no real progress on that either as yet.)

**Comment by burkmarr** [comment] 2024-07-04 10:33
@johnvanbreda - can you shed any light on the analysis below?

I'm trying to understand why no common name is being shown for _Aeshna isoceles_ records, e.g. https://irecord.org.uk/record-details?occurrence_id=36464674, and how to remedy that by setting the default common name to Norfolk Hawker. The report for the record-details page gets the common name from `cache_taxa_taxon_lists.default_common_name` and the value is null for _Aeshna isoceles_. The value of `cache_taxa_taxon_lists.default_common_name` is set by the cache_builder module by reference to `taxa_taxon_list.common_taxon_id` and this also null for _Aeshna isoceles_. As far as I can work out, `taxa_taxon_list.common_taxon_id` is set by the taxa_taxon_list ORM either via the website or from the uksi_operation module (for rename taxon, add synonym and move name operations). 

I don't know why the value of `taxa_taxon_list.common_taxon_id` is null for _Aeshna isoceles_ even though there are several existing common names for it, including Norfolk Hawker. Looking at the code in the taxa_taxon_list ORM, I think that it would be assigned a value if a new common name was added via the website, but I can't see how to specify that it be assigned from an existing common name.

**Comment by johnvanbreda** [comment] 2024-07-04 10:56
There was a rename taxon operation (sequence 58958) which would have added a new name and made it the preferred name. This operations code creates a taxa_taxon_list ORM object, populates several fields but NOT the common_taxon_id, then saves it. In the taxa_taxon_list model code, there is a postSubmit handler which will set the common taxon ID to the first saved taxon if the saved entry is a preferred name, but note that this code is only triggered if there is something called metaFields in the submission (which is a special field used to submit the common names and synonyms from the warehouse UI). So, because these fields are missing, the code which would have filled in the common taxon ID is not going to run.

I would suggest that the rename taxon operation (and possibly the others you mentioned) should fill in the common_taxon_id themselves. In this case it would be OK to fetch the common taxon ID that was used by the previous preferred name and use that. So, getTaxaForKeys can have ttl.common_taxon_id added to the list of fields it returns then $previousPreferredName will contain the common_taxon_id that can be added to the new taxa taxon list item. There will also be a script needed to fix any similar problems in the database.

Let me know if you are happy to take this on or want me to do it.

**Comment by burkmarr** [comment] 2024-07-04 11:09
Thanks @johnvanbreda - I'll take a look at it.

**Comment by burkmarr** [comment] 2024-07-04 13:02
@johnvanbreda - How does `cache_taxon_taxa_lists` get updated when uksi_operations updates `taxa_taxon_lists`? I can see that the taxa_taxon_list model enters 'task_cache_builder_taxonomy_occurrence' work_queue tasks for `cache_occurrences_functional`, but I can't see how `cache_taxon_taxa_lists` gets updated.

**Comment by johnvanbreda** [comment] 2024-07-05 09:40
@burkmarr The cache tables are updated on the next scheduled tasks run by the cache builder module - it detects changes based on the updated_on field. This is different to how the cache builder updates occurrences since the latter are updated immediately.

**Comment by DavidHepper** [comment] 2024-07-05 10:52
@burkmarr Thank you for working on this. It's been causing confusion for recorders. I'll wait until Monday (8th) and try the various combinations. 
Will existing records update automatically? Currently _Aeshna isoceles_ records (e.g. 36835027) have no Common Name.

**Comment by burkmarr** [comment] 2024-07-09 08:49
Hello @DavidHepper . I work part-time (Tues-Thurs) so I'm only just returning to this now. I'll let you know when it is done.

**Comment by burkmarr** [comment] 2024-07-09 11:30
@johnvanbreda - I made a merge request into develop branch for a fix to the uksi_operations module to address the direct updating of common_taxon)_id (https://github.com/Indicia-Team/warehouse/pull/522). 

Can I have your advice on identifying existing taxa for the script to fix this problem? I expected this SQL to match _Aeshna osoceles_ to Norfolk Hawker (along with any others that required fixing), but it doesn't because Norfolk Hawker is not marked as a preferred taxon (no synonym of _Aeshna osoceles_ is marked as preferred).

Removing the `and ttl2.preferred = true` condition does match  _Aeshna osoceles_ to Norfolk Hawker, but also to all the other common names for it.

```SQL
select t.taxon as taxon, t2.taxon as common from taxa_taxon_lists ttl
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id = ttl.taxon_meaning_id
join taxa t on t.id = ttl.taxon_id
join taxa t2 on t2.id = ttl2.taxon_id
where ttl.taxon_list_id=15
and ttl2.taxon_list_id=15
and ttl.deleted=false
and ttl.preferred=true
and ttl.allow_data_entry=true
and ttl.common_taxon_id is null
and t2.language_id != 2
and ttl2.preferred = true
order by t.taxon
```

**Comment by DavidHepper** [comment] 2024-07-09 12:43
(Probably just a typo above but this should be _isoceles_ not _osoceles_)

**Comment by johnvanbreda** [comment] 2024-07-09 14:12
@burkmarr You can't pick a default common taxon name this way, unless you just pick an arbitrary one, because there may be many common taxa that are available as you've found. What I was expecting was that you would use the common_taxon_id from one of the other names for the taxon, which should give you the value it was set to prior to the UKSI change which remove it from the accepted name. This query shows you that for 156 of the 160 taxa with a missing common taxon, there is a single name available that can be used:
```sql
select ttl.id, t.taxon, array_agg(distinct ttl2.common_taxon_id)
from taxa_taxon_lists ttl
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id=ttl.taxon_meaning_id and ttl.deleted=false
join taxa t on t.id=ttl.taxon_id and t.deleted=false
where ttl.taxon_list_id=15
and ttl.preferred=true
and ttl.common_taxon_id is null
and ttl2.taxon_list_id=15
and ttl2.common_taxon_id is not null
group by ttl.id, t.taxon
```
For the 4 remaining you may need to look at the data available and just pick the most prevalent one unless one of the possibilities is obviously better than the others.

**Comment by burkmarr** [comment] 2024-07-10 07:40
@johnvanbreda - I've had a look at this but the SQL required for the update to remedy this is beyond me. Can you do it on this occasion and post the SQL here so that I can see how you did it?

**Comment by johnvanbreda** [comment] 2024-07-10 10:36
@burkmarr I've written the following script and tried to add explanations of my thinking. 

```sql

drop table if exists proposed_common_taxon_ids;
-- Prepare a temporary table for each preferred taxon in UKSI where the common_taxon_id
-- is missing, but present on one of the other names for the organism. Include an array 
-- of all the valid common_taxon_ids from other names for the organism.
select ttl.id, t.taxon, 
	array_agg(distinct ttl2.common_taxon_id) as common_taxon_ids, 
	count(distinct ttl2.common_taxon_id) as common_taxon_id_count
into temporary proposed_common_taxon_ids
from taxa_taxon_lists ttl
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id=ttl.taxon_meaning_id and ttl.deleted=false
join taxa t on t.id=ttl.taxon_id and t.deleted=false
-- Force selection of only valid common names.
join cache_taxa_Taxon_lists cttlcommon 
	on cttlcommon.taxon_id=ttl2.common_taxon_id 
	and cttlcommon.taxon_list_id=15 
	and cttlcommon.allow_data_entry=true
	and cttlcommon.organism_key=t.organism_key
where ttl.taxon_list_id=15
and ttl.preferred=true
and ttl.common_taxon_id is null
and ttl2.taxon_list_id=15
and ttl2.common_taxon_id is not null
group by ttl.id, t.taxon;

-- Double check what the suggestion is for A. isoceles.
select * from proposed_common_taxon_ids where taxon like 'Aeshna%'
-- Returns 633193	"Aeshna isoceles"	{221137}	1
-- Looks good - Norfolk Hawker chosen.
select id, taxon, default_common_name from cache_taxa_taxon_lists where id=633193 or taxon_id=221137

-- Quick eyeball to make sure nothing obviously wrong in selections:
select p.taxon, t.taxon as proposed_common_name
from proposed_common_taxon_ids p
join taxa t on t.id=p.common_taxon_ids[1];

-- Double check there aren't cases with 2 possible common names that I'd need to manually resolve:
select * from proposed_common_taxon_ids where common_taxon_id_count>1
-- This returns 0 records so we are safe to apply the proposals.
	
-- Fix the taxa taxon list common taxon IDs where there is only 1 possibility in the data.
update taxa_taxon_lists ttl
set common_taxon_id=p.common_taxon_ids[1], updated_on=now(), updated_by_id=3
from proposed_common_taxon_ids p
where p.id=ttl.id;

-- At this point we should:
-- * wait for the scheduled tasks to run so that the taxonomy is correct.
-- * regenerate the taxa.yml file for logstash (using the new PHP script)
-- * restart logstash so it's definitely using the new file.

-- These are the affected occurrences - since the default common name is not held in the 
-- occurrence cache tables, we just need to trigger an update to change the tracking number
-- so they are updated in Elasticsearch. There should be approx. 9.5K.
update cache_occurrences_functional o
	set website_id=o.website_id
using proposed_common_taxon_ids p
where p.id=o.preferred_taxa_taxon_list_id;

-- This is the query I used to count the affected occurrences.
select count(distinct o.id) 
	from cache_occurrences_functional o
	join proposed_common_taxon_ids p on p.id=o.preferred_taxa_taxon_list_id;
```

I haven't run it yet - can you check and see if you follow and agree with the logic? Once I limited it only to valid common taxa the number of fixes was reduced to 70.

**Comment by burkmarr** [comment] 2024-07-10 11:56
@johnvanbreda - I think I can follow it all. It's really useful to see this logic with all the comments. The only thing I noticed that looked wrong is that in the first select, there isn't a check for ttl2.deleted.

Is the temporary table proposed_common_taxon_ids cleaned up automatically when the pgAdmin session ends? If so then I guess that the session needs to be kept open whilst waiting for the scheduled tasks and logstash stuff to be done before running the stuff for cache_occurrences_functional?

**Comment by BirenRathod** [comment] 2024-07-10 12:22
@burkmarr By cleaned up means, is it going to delete by itself when PgAdmin session ends? If the answer is yes then it won't be deleted by itself. you need to delete the table before exists from the PgAdmin.

**Comment by johnvanbreda** [comment] 2024-07-10 12:36
A temporary table does indeed get dropped if the session closes. But, maybe it is safer to use a permanent table then drop it manually when done, in case the connection drops or something else untoward happens?

Good spot about ttl2.deleted - the join to ttl2 has a mistake in that this should refer to ttl2.deleted at the end of the line:
```sql
join taxa_taxon_lists ttl2 on ttl2.taxon_meaning_id=ttl.taxon_meaning_id and ttl2.deleted=false
```
Plus, in the where clause there should be:
```sql
and ttl.deleted=false
```

**Comment by burkmarr** [comment] 2024-07-10 13:06
@johnvanbreda - shall I go ahead and do this with the suggested modifications?

A few more things:

1. Can taxa.yaml be replaced while logstash is running then just restart logstash?
2. Presumably taxon-paths.yml doesn't need replacing since we're not modifying the taxonomic tree - is that correct?
3. Do scheduled tasks run every 15 minutes and will all the taxonomic updates be handled together (i.e. not like work_queue processing)? 
4. I think that you restarted logstash when we did the incremental update because of my connection issues (now resolved). I can try it, but if I don't have permission, I may have to get you or Biren to do it.

**Comment by johnvanbreda** [comment] 2024-07-10 13:17
1. Yes
2. Actually, on second thoughts I would update it in case we pick up changes for any other taxonomic lists that are included, like the EBMS lists.
3. Yes.
4. Ok, let me know if you need me to do it.

> shall I go ahead and do this with the suggested modifications?

Yes, I think so.

**Comment by burkmarr** [comment] 2024-07-10 14:05
@johnvanbreda - almost there, but a glitch at the last step. This fails:
```sql
update cache_occurrences_functional o
	set website_id=o.website_id
using proposed_common_taxon_ids p
where p.id=o.preferred_taxa_taxon_list_id;
```
I'm not familiar with the using clause - can you spot what's wrong?

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/5c987b4c-422d-4092-8a65-340b846db6b1)

**Comment by johnvanbreda** [comment] 2024-07-10 14:19
Try replacing "using" with "from" - suspect I got the wrong SQL dialect!

**Comment by burkmarr** [comment] 2024-07-10 14:23
@johnvanbreda - Great, that's done. So now I guess it's just a case of waiting for ES to catch up.

**Comment by Sam-Amy** [comment] 2024-07-10 14:37
The common name Himalayan balsam (Impatiens glandulifera) is not being shown in the app (but it is on the website) - could this be related to the issue here @burkmarr or should I raise one in the app repository? 

Unrelated, but I also noticed looking in the [warehouse at this taxon,](https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=&filter-key_type=org&filter-taxa_taxon_list_id=184836&filter-taxa_taxon_list_id%3Ataxon=Impatiens+glandulifera) that there are multiple entries for each name/TVK - is this expected?

**Comment by burkmarr** [comment] 2024-07-10 14:50
@Sam-Amy I'm not sure about the app, but the multiple entries on the Warehouse doesn't look right! There are a few other problems included in this issue and I will need to return to them. It's likely to be next week now as I need to do some work on another project, but I will return to your question then.

**Comment by DavidRoy** [comment] 2024-07-10 14:54
The app will need an update to species when the uksi update has stabilised.  There's not an automatic process currently

**Comment by sacrevert** [comment] 2024-07-10 14:55
@Sam-Amy @burkmarr There's an entry for every warehouse species list on which the taxon is present. For example:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/364938
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/323689

**Comment by Sam-Amy** [comment] 2024-07-10 15:08
Thanks @sacrevert that makes sense - I havent' noticed multiple entries before but I guess as an INNS this appears on more lists than most.

**Comment by DavidHepper** [comment] 2024-07-15 12:32
Entering 'Aeshna isoceles' now works; entering 'Norfolk Hawker' now works - matching 'Aeshna isoceles'. 
There only remains the oddity reported above > https://github.com/BiologicalRecordsCentre/iRecord/issues/1617#issuecomment-2176295277 with one of the synonyms of this species showing 'NONE' in the 'Name as entered' but the species it maps to is correct. See Training Mode record 37042702.

**Comment by burkmarr** [comment] 2024-07-16 17:19
![image](https://github.com/user-attachments/assets/85e363ca-ce12-41ad-90a5-465032e18dc5)

The 'NONE' in this name derives from the value NONE in the taxa table which I suppose comes from the UKSI. There are a few entries in the UKSI_History table - all amend name operations - where the attribute field is set to NONE. I'll ask Chris what it is meant to signify. 

@johnvanbreda - presumably we don't want the value 'NONE' to be used in our taxa table? There are just 9 records in our taxa table with the attribute field set to NONE (including Anaciaschna isoceles).

**Comment by johnvanbreda** [comment] 2024-07-17 07:54
Normally, the taxon attribute is appended to the taxon name, e.g. s.l. or other similar name suffixes. We have no special code for this but I am guessing the intention is that NONE really means no attribute, or at least nothing should be added to the taxon name. Worth checking with Chris.

**Comment by burkmarr** [comment] 2024-07-17 12:57
@johnvanbreda - I confirmed with Chris that the value 'NONE' indicates the removal of a value for 'attribute' when amending a name. I'll make a code change and pull request on the uksi_operations module.

About fixing the current problems, can you comment on this workflow?

- In a temp table store occurrence IDs that link to a record in cache_taxa_taxon_lists, via taxa_taxon_list_id or preferred_taxa_taxon_list_id with a value for taxon that ends in ' NONE'.
- Update records in the taxa table that have attribute set to 'NONE' - set to null.
- Will scheduled tasks recognise the change to the taxa table and rebuild the affected cache_taxa_taxon_list records or will I have to do that explicitly with the work_queue?
- Regenerate taxa.yml.
- Restart logstash.
- Trigger logstash updates by updating the website_id field in cache_occurrences_functional where id is in the temp table.

**Comment by johnvanbreda** [comment] 2024-07-19 15:15
The workflow looks correct. 

> Will scheduled tasks recognise the change to the taxa table and rebuild the affected cache_taxa_taxon_list records or will I have to do that explicitly with the work_queue?

Yes, but you will need to set updated_on (and preferably updated_by_id) in the taxa table for the rows you change in order to trigger this. You will then need to wait ~15 minutes or so for this to take effect before the next step.

**Comment by burkmarr** [comment] 2024-07-23 14:36
@johnvanbreda - can you remind me of the best way to monitor that logstash is running okay?

I've carried out the workflow discussed above, so the ES occurrences with 'NONE' at the end of the name will start being corrected now.

**Comment by johnvanbreda** [comment] 2024-07-23 14:46
I would suggest logging onto the warehouse UI then viewing the page at Admin > Diagnostics and Maintenance. Look for the following in the REST API data feed delays section:
rest-autofeed-BRC5
rest-autofeed-BRC5SENS
rest-autofeed-BRCSMP
rest-autofeed-BRCSMPSENS

If any have a value higher than a few thousand, then it might indicate some blockage (particularly if the number just seems to go up over time and never comes down again).

**Comment by burkmarr** [comment] 2024-07-23 15:38
The uksi_operations module updated in in branch off development branch. Pull request is here: https://github.com/Indicia-Team/warehouse/pull/523

**Comment by johnvanbreda** [comment] 2024-07-24 08:01
@burkmarr I've merged the pull request into develop

**Comment by burkmarr** [comment] 2024-07-24 08:06
@DavidHepper @Sam-Amy - the specific issues identified under this umbrella issue have now either been dealt with or moved to a more specific issue. Are you both happy to close this issue?

**Comment by DavidHepper** [comment] 2024-07-24 18:25
Fine by me.
For the record: 
- While verifying records, searching for taxon 'Aeshna isoceles' or 'Anaciaeshna isoceles' each returns hits, according to the Recommended name when the record was first saved. This is OK.
- These records all show a Common Name of 'Norfolk Hawker'. This is good.
- While entering new records, trying to enter species **Anaciae...** fails to match. This is slightly unexpected but probably OK.

**Comment by sacrevert** [comment] 2024-07-25 08:14
@burkmarr the common name issue for NPMS aggregates that I mentioned above [here](https://github.com/BiologicalRecordsCentre/iRecord/issues/1617#issuecomment-2196644419) doesn't seem to be fixed yet. Is some additional process required to refresh the common names in these cases?

**Comment by burkmarr** [comment] 2024-07-25 08:26
Thanks @DavidHepper. I get a match for 'Anaciae' using iRecord's 'enter casual record' form (see image below). On what form is it failing to match?
![image](https://github.com/user-attachments/assets/c8ccceb2-5a42-49e0-a4a7-2e3aa33c8b7d)

**Comment by burkmarr** [comment] 2024-07-25 08:29
@sacrevert - isn't that covered by this new issue which I opened here? https://github.com/BiologicalRecordsCentre/iRecord/issues/1700

**Comment by sacrevert** [comment] 2024-07-25 08:31
> @sacrevert - isn't that covered by this new issue which I opened here? #1700

Sorry, missed that update when I scanned back

**Comment by DavidHepper** [comment] 2024-07-25 11:19
Yes, I agree it works on the Casual Record form but not on these two:
https://irecord.org.uk/enter-dragonfly-record
https://irecord.org.uk/enter-dragonfly-list
This suggests that the synonyms are not being treated as Odonata.

> Thanks @DavidHepper. I get a match for 'Anaciae' using iRecord's 'enter casual record' form (see image below). On what form is it failing to match?

**Comment by burkmarr** [comment] 2024-07-30 11:00
@DavidHepper - I've had a look at this and found an option on the dragonfly forms configuration which is currently limiting the available names to 'common names or preferred latin names'. 

![image](https://github.com/user-attachments/assets/d46c656d-44c7-452b-8279-b92198c3ffbe)

The general irecord page has this set to 'all names are available'. Would you like me to change the selected config option?

**Comment by DavidHepper** [comment] 2024-07-30 11:20
Thanks, @burkmarr. On consideration, that's correct. I don't want to ask for _Anaciaeschna_ to become a special case just because is was _formerly_ the preferred latin name. Looks like we're done with this one if @sacrevert is also content.

**Comment by sacrevert** [comment] 2024-07-30 11:25
@burkmarr confirmed that all NPMS/BBS things now covered elsewhere, so closing

**Closed as completed by sacrevert** 2024-07-30 11:25 UTC
