### ISSUE TITLE
BDS survey forms need a new Life Stage: Oviposition scars

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#898] opened 2020-08-05 10:05 UTC
Please add an extra life-stage abundance field for 'Oviposition scars' with code 'Sc' to our Single and List survey forms. I've deliberately made this 'scars' not 'scar' to imply that we don't want people counting each egg pouch.
The Willow Emerald Damselfly makes it presence felt with these unmistakable features on stems and small branches, especially easily seen in the winter so are often seen well outside the flight period. Currently, recorders have no suitable life stage to pick.

![image](https://user-images.githubusercontent.com/24915271/89399341-3c53ef80-d70a-11ea-881b-6e09b9a6019f.png)

The full table, in order:
**Short-code	Field Help**
Ad	Adult
Co	Copulating pair
Ov	Ovipositing female
Sc	Oviposition scars
La	Larva
Ex	Exuvia
Em	Emergent

Example photo:
![P1050117 - Chalcolestes viridis ovip marks in Alnus](https://user-images.githubusercontent.com/24915271/89399998-2561cd00-d70b-11ea-8b51-edfaee5e7f4c.JPG)

**Comment by kitenetter** [comment] 2020-08-05 11:06
@DavidHepper I've adjusted the two BDS forms on iRecord. Please confirm that these are displaying correctly (I've included a link to the BDS Willow Emerald page).

Do you want "Sc" adding to the DRN dragonfly imports as well?

Are there any other recording forms that use these terms and will also need adjusting?

**Comment by DavidHepper** [comment] 2020-08-05 12:19
Yes, please. The import spec must stay in step. We only have one import form. I'll reissue the template when this is done.
Also the iRecord App for mobile. Equally important.

**Comment by DavidHepper** [comment] 2020-08-05 15:09
I've tested both forms successfully in Training Mode and created record 17122270. 

- This record can be seen in **Verify - old** and **Explorer > All records** but has not appeared after two hours in **Verify**. Background checks are slow today but that's probably a separate issue.

- This record appears in a Download with a Survey restriction to **iRecord > iRecord Dragonflies** showing the new Sc field and its correct value but at the end of the list (a minor issue) in spreadsheet column BE instead of BB:

![image](https://user-images.githubusercontent.com/24915271/89429606-acc43600-d735-11ea-9855-ee4d9d1beef1.png)

**Comment by kitenetter** [comment] 2020-08-05 15:33
I've added the new stage to the DRN imports (but haven't tested the import process).

We will add the new stage to the app when the next round of updates takes place - I don't yet know when that will be.

The delays to records appearing in **Verify** are a separate issue, see:
https://www.brc.ac.uk/irecord/node/8128

I don't know what controls the column ordering in the download output - @johnvanbreda is this something I can adjust or shall I raise it as a separate issue?

**Comment by johnvanbreda** [comment] 2020-08-05 16:04
@kitenetter I think the order of attributes will be as defined on the setup attributes page (https://warehouse1.indicia.org.uk/index.php/attribute_by_survey/346?type=occurrence) but only if you've ever actually used this page to set the attribute order.

**Comment by kitenetter** [comment] 2020-08-05 16:38
@johnvanbreda the attributes are correctly ordered on that warehouse page, but I'm not sure what you mean by "if you've ever actually used this page to set the attribute order". I think the order on the warehouse page does feed through to the order on the website recording form, but presumably it doesn't feed through to the download given David's screenshot above?

**Comment by johnvanbreda** [comment] 2020-08-05 19:00
@kitenetter I've looked at the code - I think the sort order I mentioned isn't actually picked up in this case. Can this be added as a separate issue for prioritisation please?

**Comment by DavidHepper** [comment] 2020-10-14 12:53
I tried on 11 Oct a CSV import that included column 'Sc' but it prompted for field matching and couldn't offer a match from 'Occurrence Custom Attributes' where the other life-stage abundance fields are. The import form is 'DRN dragonfly imports.

**Comment by DavidHepper** [comment] 2021-01-28 13:56
@kitenetter this has become a serious issue. We're at the peak time for spreadsheet imports and **Sc** cannot be matched. The longer this goes on the more records will need to be edited manually.

**Comment by kitenetter** [comment] 2021-01-28 15:27
@DavidHepper I've made an edit to the import form that should allow Sc to be imported. It hasn't appeared on the form yet, which I'm hoping is just a caching issue. I will try again later this afternoon and let you know.

**Comment by kitenetter** [comment] 2021-01-28 16:28
@johnvanbreda I've added occAttr:842 to the Field/column mappings for survey ID 346 in the import form, but it hasn't yet appeared in the list of occurrence custom attributes for field mapping.

Does it take longer than an hour for this sort of update to be reflected in the form? Or is there another problem we need to fix?

**Comment by johnvanbreda** [comment] 2021-01-28 19:54
@kitenetter The problem was that, because this attribute is a lookup rather than free text, the attribute name required is occAttr:fk_842. Admittedly we should probably make the code automatically handle this so it is easier to setup. I've fixed the import page for you.

**Comment by kitenetter** [comment] 2021-01-29 14:56
@DavidHepper the import process seems to be working for Sc now - sorry it has taken so long to get to this point.

@johnvanbreda I thought that I had set up the Sc attribute in the same way as the other life stage attributes, but I see now that while I've used a termlist for Sc, the other attributes are not set up with a termlist. However, in the data entry form they all have the same dropdown list appearing. How is the dropdown list controlled for those attributes that do not have a linked termlist?

**Comment by DavidHepper** [comment] 2021-02-03 16:35
@kitenetter:
1. Currently I have to match an 'Sc' column header to 'Sc (from controlled termlist)'. Will it stay like this? I'd prefer to reissue the template with just 'Sc'.
2. I've just tried such to import a one-row CSV with 'Sc' column in Training Mode (starting at ~ 2021-02-03 16:26) and it has hung at "Preparing to upload.."

**Comment by kitenetter** [comment] 2021-02-03 16:46
I'm afraid this is going to have to be a question for @johnvanbreda again - I don't know how else to set up the number range termlists.

**Comment by johnvanbreda** [comment] 2021-02-04 09:51
@DavidHepper I couldn't reproduce the problem you had where it hung importing a single record. Can you send me the file so I can reproduce it myself please?

Regarding the Sc field - it will still automap the column if you use just Sc in your template. The reason why this field is different in the drop down list of fields to map to is for some reason the Sc field uses a controlled termlist of number ranges, whereas the other fields are just plaintext fields. The "(from controlled termlist)" suffix is just an explanation that the value you provide must match one of the terms in the associated termlist.

**Comment by kitenetter** [comment] 2021-02-04 10:04
@johnvanbreda is it possible to explain how the other stages, that do not use the controlled termlist, are able to provide a termlist on the recording forms? If I understood how to do that I could change the Sc term so that it doesn't use the controlled termlist and behaves the same way as the other stage attributes.

**Comment by johnvanbreda** [comment] 2021-02-04 10:44
@kitenetter Yes, the DRN import survey and the one on the Enter a dragonfly record form are different survey datasets with different attributes. Presumably to allow flexibility for historic imported data, the DRN import dataset uses text attributes whereas the recording form uses lookup attributes.

**Comment by kitenetter** [comment] 2021-02-04 10:52
Thanks @johnvanbreda - that makes perfect sense and is obvious now you've pointed it out to me, apologies for being slow on the uptake.

@DavidHepper it looks like the best solution is for me to create a new "Sc" attribute for the DRN imports, that does not link to a defined termlist. I will do that shortly unless you foresee any complications.

**Comment by kitenetter** [comment] 2021-02-07 10:06
@DavidHepper the DRN dragonfly imports process should now import into a new, free text, version of Sc, so that the behaviour for this attribute matches the other stage attributes.

At the moment, downloads of the DRN dragonfly imports will include a column for the old Sc (lookup) terms and the new Sc (free text) terms. So we need to transfer the data as follows, and then remove the lookup attribute from the DRN survey:
- All data that is stored in occurrence attribute ID 842 (Sc) for survey ID 346 (DRN dragonfly imports) now needs to be moved to occurrence attribute ID 864 (Sc).

I think that is straightforward to do but I will check what is needed before assigning that task.

**Comment by DavidHepper** [comment] 2021-03-26 17:09
Thanks. We just need it to work in the same way as the other attributes. There is no historical data to be transferred and I don't know whether Sc has even been used yet. 
A small number of existing records will need to be found and edited manually to transfer a value from a random other life stage to the new Sc field, based on free-text information in the occurrence comment field, but that's my problem.

**Comment by kitenetter** [comment] 2021-11-05 21:21
@DavidHepper I have now removed the incorrect (lookup list) version of "Sc" from the DRN import survey. There were no records that used the incorrect version. It should now be possible to import into the "Sc" stage attribute in the same way as the others, and you should only see one version of the "Sc" attribute in the Edit view following import.

I think we can close this issue but let me know if there are any remaining concerns.

**Closed** 2023-05-02 21:01 UTC
Labels: feature request, scale:small
