### ISSUE TITLE
Verify: why no Edit button for some records?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#147] opened 2017-01-25 13:56 UTC
While in Verify it is unclear why the Edit button disappears for some records with status 'Not reviewed'. What are the rules for this? 
Example: I am unable to edit the record with ID = 2530697 although I have Verifier access to dragonflies where the survey is BDS Advanced Records.

**Comment by johnvanbreda** [comment] 2017-01-25 15:03
Hi @DavidHepper 
The edit function only works for records added via iRecord itself, since we don't have access to the forms used on other sites. You can update the determination though.
Regards
John

**Comment by kitenetter** [comment] 2017-01-25 15:30
@johnvanbreda if we were to set up a duplicate of the BDS form on iRecord would we be able to make these records editable? (But presumably the records are 'hard-coded' to the form they originated from, so this might not be straightforward?)

Presumably the original recorders also can't edit their records as they have no way of getting back to the data via the BDS website?

**Comment by johnvanbreda** [comment] 2017-01-25 15:50
This is a special case because the original forms are no longer accessible. If acceptable to the recorders, a fairly quick solution would be to recreate the forms on iRecord then move the records from the BDS website to iRecord by updating their website ID, so they become editable. The enabling of the edit button is linked to the website associated with the record so we either have to move the records across as suggested here, or write some code to enable this button in certain special circumstances.

**Comment by kitenetter** [comment] 2017-01-25 17:34
@johnvanbreda in this case, where the original forms are no longer available, it does seem to make sense to recreate the forms within iRecord as you suggest (as long as @DavidHepper agrees).

There are wider issues as well. We have a number of recording schemes who wish to bring data in to the iRecord warehouse but wish to set up separate warehouse 'website' partitions in which to store the data, so that the appropriate website agreements can be put in place re data sharing etc. Does this mean that any set of data that is stored within a 'website' partition becomes unavailable for editing via iRecord?

If so we will need a more general solution to this, as the schemes that import data will need to be able to edit it.

**Comment by DavidHepper** [comment] 2017-01-25 17:35
Thanks, John. I'd much rather we migrate the records to the newer iRecord 
Website/Surveys and delete the old ones. We're then left with only three 
dragonfly surveys, plus 'iRecord General'. Much less confusing.

**Comment by kitenetter** [comment] 2017-02-06 13:36
@johnvanbreda What happens next, should I recreate appropriate forms for the BDS data, or will we be able to link to the existing BDS forms on iRecord, or is it better to wait for the proposed #154 generic editing form?

@DavidHepper do you know how well the data structure from the old BDS form matches that for the new forms? (Don't worry if you don't, I can work it out if needed).

**Comment by MNSmith** [comment] 2017-03-14 13:12
I understand the explanation that "we don't have access to forms used on other sites", It does seem a little odd that there is no edit facility for Verifiers considering a) most of these forms were a) built by BRC for use on these other sites (I'm thinking here of the ones on the BWARS website for example) and b) all these forms are adding data to iRecord.

One of the problems with forms is that they are "stand-alone" records and that the majority of users do not have iRecord accounts, making querying any records from these more difficult.  While we can sometimes amend the species on the form, what we can't do is ask the user to go back and make other changes to them.  The main issue here are incorrect grid references where you have a good record with full details that could be accepted but for some reason the grid ref is wildly incorrect and the dot is in the sea for example.  

The only way to manage this at present is for the Verifer to manually enter the entire record again with the correct geo-location via their own iRecord account, cross reference comments between the two and then "reject" the original record. Not particularly efficient.  Having edit ability on form generated records, at least for the geo-location, would be very helpful.

**Comment by kitenetter** [comment] 2017-06-02 11:46
Relates to #154

**Comment by DavidRoy** [comment] 2017-09-21 15:29
Thanks John.  Closing issue, but may reopen if David Hepper finds any issues

**Closed by DavidRoy** 2017-09-21 15:29 UTC
Labels: enhancement
