### ISSUE TITLE
UKSI update has knocked out Common Darter - Sympetrum striolatum

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#909] opened 2020-08-18 15:55 UTC
Please reinstate the English name "Common Darter" against S. striolatum > https://www.nhm.ac.uk/our-science/data/uk-species/species/sympetrum_striolatum.html
We requested UKSI to make S. nigrescens (Highland Darter) a deprecated synonym of S. striolatum. This appears to have been done as neither the scientific nor the common name can be entered in iRecord. But is seems to have happened for S. striolatum, too, and we're approaching peak season for recording it. 
In 'Explore all records' the species is available to filter under 'Species and higher taxa' but only under its scientific name. However, selecting it only shows records of this species from 2019 and earlier.
I've been through iRecord checking _all_ the recommended common names of all species and only found two migrant rarities to be missing. These ought to be discussed within BDS first.

**Comment by burkmarr** [comment] 2020-08-19 09:23
@johnvanbreda - for some reason this problem is evident in the main warehouse but not on dev. In the main warehouse there is no record for Common Darter in the cache_taxa_taxon_lists table (for UKSI) because, for some reason, the correspondeding record in taxa_taxon_lists is marked as deleted. I will do some more investigation into this. In the meantime can I fix the problem for this taxon by unsetting the delete flag and then submitting a work_queue task of type 'task_cache_builder_update'?

**Comment by DavidHepper** [comment] 2020-08-19 09:42
I'm getting bombarded by users stuck on this! Quick and dirty? Yes, please. How long will 'task_cache_builder_update' take?

**Comment by johnvanbreda** [comment] 2020-08-19 10:07
@burkmar yes, unsetting the deleted flag will work. You can either set updated_on=now() or submit a work_queue task.

The tables in the UKSI schema are useful for diagnosis. The fact that Common Darter is in the uksi.all_names table implies that the extraction from Access worked OK. Therefore I would suspect the scripts that synchronise the imported data in the uksi schema with the taxon data in Indicia. I've scanned all the scripts and I think only script 17 can actually set the deleted flag on taxa_taxon_lists. It would only do this if there are no records (which there are lots of) so I can't see why the UKSI scripts would have deleted this entry.

**Comment by johnvanbreda** [comment] 2020-08-19 10:13
@burkmarr In light of David's comment, I think setting updated_on will be quicker, because the cache_builder is running more or less up to date, but the work_queue has lots of stuff to do to catch up after imports. So I've just set the updated_on to now() for you (seeing as you've done the delete flag already).

@DavidHepper it should hopefully be done within an hour.

**Comment by burkmarr** [comment] 2020-08-19 10:20
@johnvanbreda - I had already submitted a work_queue task before I saw your posts. I set it to priority 1. After I saw you fist post, but before I saw second, I also set the updated_on field!

I've got some other things to do to day, but I will return to this to see if there is a wider problem.

**Comment by johnvanbreda** [comment] 2020-08-19 10:50
@DavidHepper Common Darter is available for data entry again now.

**Comment by Mike-Averill** [comment] 2020-08-19 13:43
filtering records under common Name as *Common Darter* still doesn't pick up the records- is that to be expected?

**Comment by johnvanbreda** [comment] 2020-08-19 14:02
Thanks for spotting that @Mike-Averill, it had indeed lost the link between the accepted name and it's common name, which is obvious when you think about it. I've relinked it - it will take half an hour or so to update.

**Comment by johnvanbreda** [comment] 2020-08-19 14:09
@burkmarr I just checked the Elasticsearch taxon lookup data which I think I re-built just after you did the UKSI update (on 3rd August if that helps). The missing common name was correctly linked to S. striolatum which makes me think that the deletion might have happened separately after the UKSI update.

**Comment by burkmarr** [comment] 2020-08-19 15:59
@johnvanbreda - how does updating the updated_on field trigger an update of the cache tables?

**Comment by johnvanbreda** [comment] 2020-08-19 16:30
@burkmarr If you search the cache builder module code for get_changed_items_query you'll see that it does a scan for the updated_on flag when deciding which parts of cache_taxa_taxon_lists to rebuild during a scheduled tasks run.

**Comment by DavidHepper** [comment] 2020-09-02 11:45
This has been working since John's update. I'm happy to close this.

**Comment by DavidHepper** [comment] 2021-02-06 10:39
The recent UKSI update has knocked out Common Darter again, in the same way as before. Please relink and make a note to check it after future updates. If this is a fault with UKSI itself I'm happy to take it up with Chris R. or others, if you wish.

**Comment by johnvanbreda** [comment] 2021-02-07 17:09
As before I have suspicions that this was not directly caused by the UKSI update because immediately after the update I rebuild the lookup tables for Elasticsearch extraction and the data seems complete in the lookup tables. At least one of the changes may have occurred on 3rd Feb according to the date stamps on the data.

I've repaired it using the following SQL:
```sql
update taxa_taxon_lists set deleted=false, updated_on=now() where id in (
select ttl.id
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id
and t.search_code in (
  select input_taxon_version_key from uksi.all_names where recommended_taxon_version_key='NBNSYS0000005645'
) and ttl.updated_on>'2021-01-03'
)
```

**Comment by DavidHepper** [comment] 2021-02-08 09:20
That has improved matters but not completely:
- On a form I now enter 'Sympetrum striolatum' and it offers an exact match;
- On a form I now enter 'Common Darter' but it only offers "Common/ Highland Darter Dragonfly". This is not an exact match, so imports of this name will fail.
![image](https://user-images.githubusercontent.com/24915271/107199773-ba14f280-69ee-11eb-8706-7ed2f33b2117.png)

**Comment by DavidHepper** [comment] 2021-02-08 09:21
Please reopen.

**Comment by johnvanbreda** [comment] 2021-02-08 09:57
Should be sorted - will take a few minutes to reappear in the system properly.

Just to reassure you that I think I have found the issue relating to taxonomy editing which caused this in the first place so it shouldn't happen again.

**Comment by DavidHepper** [comment] 2021-02-08 10:42
Thanks, John. Good to hear that you've found the cause.
I'm seeing the expected options now:
![image](https://user-images.githubusercontent.com/24915271/107208999-33661280-69fa-11eb-8eaf-3a486c3c44b1.png)

**Comment by DavidHepper** [comment] 2021-02-10 10:21
I've retested this today and the name 'Common Darter' is also showing again for records recently imported as 'Sympetrum striolatum', e.g. ID 18807446. Happy to close.

**Comment by DavidHepper** [comment] 2021-03-25 15:05
I've found another knock-on problem with the fix for this species. All records of _Sympetrum striolatum_ that were processed by the script above on 07/02/2021 have had their **Vice County** number cleared and now belong to no VC. This is preventing them from being visible to the CDR in Verify. Please re-run the script for assignment to VC for this species.

**Comment by johnvanbreda** [comment] 2021-04-22 10:29
@DavidHepper all the *S. striolatum* records that had no VC have been re-queued for indexing. They should be done in an hour or so.

**Closed** 2022-12-28 23:00 UTC
