### ISSUE TITLE
Verify: filter on 'Where > Map reference' requires Apply to be clicked twice

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#779] opened 2020-01-22 17:33 UTC
I'm looking for specific map references. The pearl juggle refresh doesn't occur unless I go back into the Where filter criterion a second time and click Apply again. All other filter params are default.
Same behaviour with both classic and ES Verify.
Using Firefox 72 (64-bit).

**Comment by kitenetter** [comment] 2023-05-02 20:42
Unable to reproduce this - let me know if it is still an issue. Closing.

**Closed by kitenetter** 2023-05-02 20:42 UTC

**Comment by kitenetter** [comment] 2023-05-03 10:25
@DavidHepper the problem with incorrect grid ref square filtering is covered in #521 but I'm not sure if you are still seeing a problem with the "pearl juggle refresh" (which I don't understand) and having to apply a filter twice?

**Comment by DavidHepper** [comment] 2023-05-03 10:32
It's a bit hard to tell when it doesn't produce the right results. Let's close this one and I'll try again when #521 is fixed.
