### ISSUE TITLE
Pantheon D9 site bugs

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1178] opened 2021-11-24 16:35 UTC
https://live-brc-irecord.pantheonsite.io/all-records

- [x] the map squares are not in the right place?
![iR d9](https://user-images.githubusercontent.com/2699478/143278321-f88afab6-da52-4f61-9bbd-f51af9dbf0e3.png)

**Comment by DavidRoy** [comment] 2021-11-24 16:54
home page problems
- [ ] i'm seeing repeated observations in latest list
- [ ] the screen does not adapt to screen size changes?
- [ ] 
![iR d9 #2](https://user-images.githubusercontent.com/2699478/143281612-38c61c57-60d4-4496-947e-8e2578729fe3.png)

**Comment by BirenRathod** [comment] 2021-11-24 17:11
@johnvanbreda Is it something you need to look at it?

**Comment by kitenetter** [comment] 2021-11-24 17:20
@johnvanbreda the repeated records could be another instance of #1174 - I've had a couple of other similar reports (from before the move to D9).

**Comment by kitenetter** [comment] 2021-11-24 17:22
Ignore previous comment - the Small White records are not duplicates, they are from different sections of a butterfly transect.

**Comment by kitenetter** [comment] 2021-11-24 17:25
- [] I'm getting "Elasticsearch query failed" when I try to access my verification page.

**Comment by BirenRathod** [comment] 2021-11-24 17:31
@DavidRoy @kitenetter @johnvanbreda bit strange, these are all problems only exists for LIVE env even though I cloned this site from TEST env.

**Comment by BirenRathod** [comment] 2021-11-24 17:34
> * [ ]  I'm getting "Elasticsearch query failed" when I try to access my verification page.

Sorry not this one which I'm looking into.

**Comment by BirenRathod** [comment] 2021-11-24 17:50
> @DavidRoy @kitenetter @johnvanbreda bit strange, these are all problems only exists for LIVE env even though I cloned this site from TEST env.

Ignore this comment.

**Comment by kitenetter** [comment] 2021-11-24 18:07
If I log in under my personal account ("Martin C. Harvey") and go to the main verification page, I am still seeing the Elasticsearch error message, and no records are displayed.

If I log in under my admin account ("iRecord support") and go to the main verification page, there is no error message and I can see all the records. The problem here is that the iNaturalist records are being displayed on the main verification page as well as on the iNaturalist verification page.

**Comment by johnvanbreda** [comment] 2021-11-24 18:09
I tried to visit the all records page. First time I tried I saw a message "The application did not respond in time.".

**Comment by johnvanbreda** [comment] 2021-11-24 18:10
Enter a casual record defaults to outline of Dorset on my account, with map tiles showing pink (i.e. broken).

**Comment by johnvanbreda** [comment] 2021-11-24 19:09
@BirenRathod I've fixed the problem with the map alignment in the original post above. This was because the style.css file contains a global style for all images:
```css
img {
  margin: 8px;
}
```

Because this is not targeted at any particular image, it affects all images including the layout of map tiles drawn by Leaflet, shifting them by 8 pixels in both directions. I've removed this style - do you know why it was added and if we need a more specific style for some images?

Also, I've pushed the commit, but there are other commits relating to the redirect waiting to be applied to Live, so I cannot apply my commit to fix the live site. Can your commits relating to redirection be applied?

**Comment by johnvanbreda** [comment] 2021-11-24 19:20
I've fixed the main verification page so it no longer shows iNaturalist records. For some reason this configuration change had not been migrated even though it was done a while back.

**Comment by johnvanbreda** [comment] 2021-11-24 19:27
@kitenetter I've fixed the Elasticsearch errors on the verification pages for non-admin users.

The 2 verification pages had incorrect permission settings on the Edit tab. @BirenRathod is it possible that other page settings haven't migrated correctly?

**Comment by johnvanbreda** [comment] 2021-11-24 19:35
@BirenRathod I think the OS Maps layer is broken on the data entry pages, not because there is anything wrong, but because the URL is locked to the licence. So it won't work from a different URL unless the licence is updated.

**Comment by BirenRathod** [comment] 2021-11-24 20:57
> @BirenRathod I've fixed the problem with the map alignment in the original post above. This was because the style.css file contains a global style for all images:
> ```css
> img {
>   margin: 8px;
> }
> ```
> 
> Because this is not targeted at any particular image, it affects all images including the layout of map tiles drawn by Leaflet, shifting them by 8 pixels in both directions. I've removed this style - do you know why it was added and if we need a more specific style for some images?
> 
> Also, I've pushed the commit, but there are other commits relating to the redirect waiting to be applied to Live, so I cannot apply my commit to fix the live site. Can your commits relating to redirection be applied?
> 

It has been added for images use across whole website. If We remove then text & images will submerge. 

Also, for time being until propagation of url will finish, we should avoid pushing commit on live but you can check that on TEST env.

**Comment by BirenRathod** [comment] 2021-11-24 20:59
> @BirenRathod I think the OS Maps layer is broken on the data entry pages, not because there is anything wrong, but because the URL is locked to the licence. So it won't work from a different URL unless the licence is updated.

URL is going to change, so I will check tomorrow a license first.

**Comment by BirenRathod** [comment] 2021-11-24 21:01
> @kitenetter I've fixed the Elasticsearch errors on the verification pages for non-admin users.
> 
> The 2 verification pages had incorrect permission settings on the Edit tab. @BirenRathod is it possible that other page settings haven't migrated correctly?

But this problem occurs on TEST env too.

**Comment by BirenRathod** [comment] 2021-11-24 21:03
> @kitenetter I've fixed the Elasticsearch errors on the verification pages for non-admin users.
> 
> The 2 verification pages had incorrect permission settings on the Edit tab. @BirenRathod is it possible that other page settings haven't migrated correctly?

Yes, I know it had been fixed on TEST env. Can I ask you which permission have you fixed?

**Comment by johnvanbreda** [comment] 2021-11-25 09:36
@BirenRathod 

> Yes, I know it had been fixed on TEST env. Can I ask you which permission have you fixed?

On the Edit tab for both verification pages - PERMISSION SETTINGS - My records download permission and All records download permission were both set to the wrong values (the default I think), so I've changed these to set the same permission as used for controlling access to the page.

**Comment by johnvanbreda** [comment] 2021-11-26 11:12
@BirenRathod One thing that’s missing on the new iRecord is a warning notice that you are in training mode.  There is a hook at the end of the iform.module file which should do this but it doesn’t seem to be working.

**Comment by BirenRathod** [comment] 2021-11-26 11:18
@johnvanbreda I also noticed that if I save any changes in indicia form, it doesn't save and this happens on all sites (DEV, TEST & LIVE). Did you change anything in your last commit?

**Comment by johnvanbreda** [comment] 2021-11-26 11:25
I'm not aware of changing anything that could affect that @BirenRathod.

**Comment by BirenRathod** [comment] 2021-11-26 11:29
@johnvanbreda I only tried to save by changing map option, so now idea if there is a problem there. It was working fine when I mailed you all yesterday of resolving pink map layer.

**Comment by BirenRathod** [comment] 2021-11-26 11:51
@johnvanbreda I just created test iform page on TEST env and I found out that if I select base map layers "Dynamics (OpenstreetMap > Ordnance Survey Leisure > Google Satellite)" , The form doesn't save with that option and select automatically "Dynamic (OpenStreetMap > Google Satellite)" instead. I don't know if this is expected. If not then there could be a bug in the code.

**Comment by johnvanbreda** [comment] 2021-11-26 12:15
@BirenRathod I'm taking a look now - it seems that the map layer config won't save but other stuff is OK.

Can you please fix https://irecord.org.uk/admin/reports/dblog/event/44168 because this type of error is swamping the Drupal logs.

**Comment by johnvanbreda** [comment] 2021-11-26 12:18
@BirenRathod the problem saving the map settings is because the iform_user_ui_options module has a configuration in /files/iform_user_ui_options/map.json which forces the map layers. The D7 version of this message displayed a warning so you knew that the settings being overridden on the Edit tab were locked.

**Comment by BirenRathod** [comment] 2021-11-26 12:20
> @BirenRathod I'm taking a look now - it seems that the map layer config won't save but other stuff is OK.
> 
> Can you please fix https://irecord.org.uk/admin/reports/dblog/event/44168 because this type of error is swamping the Drupal logs.

Sorry I have deleted all messages before you posted this issue. Can I ask you how can I reproduce this?

**Comment by BirenRathod** [comment] 2021-11-26 12:24
> @BirenRathod One thing that’s missing on the new iRecord is a warning notice that you are in training mode. There is a hook at the end of the iform.module file which should do this but it doesn’t seem to be working.

@johnvanbreda I have enabled my account in training mode and I can see warning notice on home page. so what is the issue here?

**Comment by johnvanbreda** [comment] 2021-11-26 12:26
@BirenRathod look in the Drupal logs - there are lots of errors that look like "User notice: Key file "file:///files/private/public.key…"

**Comment by BirenRathod** [comment] 2021-11-26 12:29
> @BirenRathod look in the Drupal logs - there are lots of errors that look like "User notice: Key file "file:///files/private/public.key…"

@johnvanbreda That is due to bug in  simple_oauth module. I had a chat with @kazlauskis and he suggested at present nothing we can do. @kazlauskis Any suggestion about it?

**Comment by kazlauskis** [comment] 2021-11-26 12:46
This is a Pantheon limitation. https://pantheon.io/docs/modules-known-issues#simple-oauth--oauth-20

What I have done to some sites is to comment out [this block of code](https://github.com/thephpleague/oauth2-server/blob/e184691ded987c00966e341ac09c46ceeae0b27f/src/CryptKey.php#L51) in the oauth2-server lib. But that is a temporary fix as it's typically reverted when the library is updated so I don't know a better solution yet.

**Comment by johnvanbreda** [comment] 2021-11-26 12:48
@BirenRathod about the training mode it didn't work for my site which was in training mode before the migration, but it works now if I turn off the flag and turn it on again. I think it's OK to leave this issue for now as maybe just a migration quirk.

**Comment by BirenRathod** [comment] 2021-11-26 12:51
> This is a Pantheon limitation. https://pantheon.io/docs/modules-known-issues#simple-oauth--oauth-20
> 
> What I have done to some sites is to comment out [this block of code](https://github.com/thephpleague/oauth2-server/blob/e184691ded987c00966e341ac09c46ceeae0b27f/src/CryptKey.php#L51) in the oauth2-server lib. But that is a temporary fix as it's typically reverted when the library is updated so I don't know a better solution yet.

@kazlauskis I will patch that code as simple_oauth module in custom folder , so it won't be updated in future unless moved with contrib modules.
@johnvanbreda I will let you know once done this.

**Comment by johnvanbreda** [comment] 2021-11-26 13:37
@BirenRathod unfortunately I have the training mode activated again and definitely no warning message.

**Comment by BirenRathod** [comment] 2021-11-26 16:11
@johnvanbreda I have activated using training mode multiple times and it shows warning message every time. Found no problem.

**Comment by kitenetter** [comment] 2021-11-26 16:45
The training mode warning seems to be working for me as well, having tested it for my personal account and the iRecord support account, using Firefox.

The only anomaly I noticed was that when I go in to edit my account and to switch training mode off, and then click Save, I am still seeing the training warning banner after the Save takes effect. However, when I navigate away from the account page the warning banner disappears, as expected.

**Comment by BirenRathod** [comment] 2021-11-26 16:56
@kitenetter That warning message appears when landed on your account page. Once you switch it off and save, you need to refresh the page.

**Comment by johnvanbreda** [comment] 2021-11-28 17:16
To reproduce the training mode - open 2 different browsers (e.g. Edge and Chrome), one logged in as admin, one as yourself. Using your own account, activate training mode. On the browser logged in as admin, masquerade as yourself. You can now see training data only, but no message appears.

This may be some weird interaction with the Masquerade module, so probably not a priority.

**Comment by BirenRathod** [comment] 2021-11-29 09:59
> > This is a Pantheon limitation. https://pantheon.io/docs/modules-known-issues#simple-oauth--oauth-20
> > What I have done to some sites is to comment out [this block of code](https://github.com/thephpleague/oauth2-server/blob/e184691ded987c00966e341ac09c46ceeae0b27f/src/CryptKey.php#L51) in the oauth2-server lib. But that is a temporary fix as it's typically reverted when the library is updated so I don't know a better solution yet.
> 
> @kazlauskis I will patch that code as simple_oauth module in custom folder , so it won't be updated in future unless moved with contrib modules. @johnvanbreda I will let you know once done this.

I know, I mentioned this to amend code but changes required are not in simple_oauth module but It is in one of the plugin called oauth2_server used by simple_oauth module. In Drupal upstream, any plugin used by contrib modules manage by composer which has integrated with Pantheon, so to make any change is not possible. 
So @johnvanbreda those error logs will be appeared continuously.

**Comment by johnvanbreda** [comment] 2021-11-29 10:13
@BirenRathod OK - though I think it may be possible to apply a custom patch in the composer.json for the upstream?

**Comment by BirenRathod** [comment] 2021-11-29 10:17
@johnvanbreda No that is an option too.

**Comment by BirenRathod** [comment] 2021-11-29 10:21
Sorry I mean, that is not an option.

**Comment by BirenRathod** [comment] 2021-11-30 16:45
> This is a Pantheon limitation. https://pantheon.io/docs/modules-known-issues#simple-oauth--oauth-20
> 
> What I have done to some sites is to comment out [this block of code](https://github.com/thephpleague/oauth2-server/blob/e184691ded987c00966e341ac09c46ceeae0b27f/src/CryptKey.php#L51) in the oauth2-server lib. But that is a temporary fix as it's typically reverted when the library is updated so I don't know a better solution yet.

@kazlauskis you suggested to above option but that is not an option. I found discussion having this issue on Drupal, see this link -> https://www.drupal.org/project/simple_oauth/issues/3021054

As per this if we could upgrade simple_oauth module to version 5.0.5 would work. Can you check compatibility with your code for mobile apps?

**Comment by kazlauskis** [comment] 2021-12-02 10:18
Just to say that I was looking into the upgrading of the simple_oauth module yesterday and I will continue testing it today.

**Comment by BirenRathod** [comment] 2021-12-02 10:24
@kazlauskis Please test this for all other websites (like fitcount, european mammals, e-surveyors etc.) too because upgrade will be released through pantheon upstream. Release will be impacted of all those websites using simple_oauth module.

**Comment by kazlauskis** [comment] 2021-12-02 13:43
@BirenRathod some of the websites use v3 of the module and upgrading to v4+ requires some changes to the apps so I won't have the time to upgrade it all any time soon. Can we limit this to the iRecord site for now?

**Comment by BirenRathod** [comment] 2021-12-02 13:53
@kazlauskis That is the difficult part to keep track of individual site. So try to keep align update for all those apps for your future update, so I can synchronised my update in upstream too. 

Only this time I will make change in iRecord, which is require as concentration on real problems don't get lose in all those notices generate by Drupal logs.

**Comment by BirenRathod** [comment] 2021-12-14 14:01
@kazlauskis You can do that in here -> https://github.com/NERC-CEH/pantheon-brc-core-d9-upstream 
The module is already added in custom folder. 

Careful when you add or modify in upstream, it will be updated on to all sites. so if that is ok, you can go ahead.

**Comment by kazlauskis** [comment] 2021-12-14 14:07
I don't want it to update all sites, just the iRecord one, how can I do that?

**Comment by BirenRathod** [comment] 2021-12-14 14:10
@kazlauskis you can use Pantheon's iRecord repository. you can access URL from Pantheon. This is the same way you can do as you update code for indicia_api or iform.

**Comment by kazlauskis** [comment] 2021-12-14 14:33
This module version requires an update to some underlying libraries are installed through composer. It is unclear to me how you typically manage the modules and updates so I would feel more comfortable if you took care of this instead.

**Comment by BirenRathod** [comment] 2022-01-18 11:28
@kazlauskis This is not possible to update libraries which is relate simple_oauth. It can only done via upstream. If I do that then we need to upgrade the module too.

@johnvanbreda The problem with user notice: key has been resolved by using dblog_filter module. it has now stopped creating those logs and site produced now only relevant messages.

I will close this issue. if we need we can create another issue if there is any bug or problem related to Pantheon irecord.

**Comment by BirenRathod** [comment] 2022-01-18 11:28
I will close this issue. if we need we can create another issue if there is any bug or problem related to Pantheon irecord.

**Closed by BirenRathod** 2022-01-18 11:28 UTC
