### ISSUE TITLE
Elastisearch - Recorder name searches.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#589] opened 2019-05-05 22:49 UTC
The Wildcard / * name search facility appears to work differently in the Elastisearch window compared to the old Verification window.  NOTE - the Wildcard "star" character seems to be operating as some sort of code in this forum, converting normal text to italic text if used on both sides of a work or phrase  - hence the additions

Looking at sorting / selecting from the following 3 Recorder names:

Bailey, Mike
bailey, steven
James Bailey

Old Grid.
"bailey" returns
Bailey, Mike
bailey, steven

"bailey, M" returns
Bailey, Mike

"*bailey*" returns  (star - bailey - star)
Bailey, Mike
bailey, steven
James Bailey

Elastisearch page:

"bailey" returns
Bailey, Mike
bailey, steven
James Bailey

"bailey, M" returns
<null> - no records

"bailey, M *" returns    (bailey, M + star)
<null> - no records

"*bailey*" returns  (star + bailey + star)
Bailey, Mike
bailey, steven
James Bailey

We don't seem to be able to use the wildcard to select from a potential list in the same way we can at present in the old grid.  It would be handy if we could.

**Comment by johnvanbreda** [comment] 2019-05-11 10:37
You can do the following:
```
event.recorded_by:Bailey AND event.recorded_by:M*
```
When you do a phrase in quotes, e.g. "Bailey, M" or "Bailey, M*" this is interpreted as an exact phrase match. To use wild cards you have to search on the analysed terms, so each term has to be on it's own. You can specify the fields to search in by putting it before the colon. Listing the available fields somewhere would be handy.

Also see the outstanding task https://github.com/BiologicalRecordsCentre/iRecord/issues/555. @kitenetter - you might like to try out the Simple Query String syntax which is a simpler alternative - see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html. We could always make this a user choice.

**Comment by MNSmith** [comment] 2019-05-11 10:42
When doing searches on the system I'm not using quotes, these are just being used in this forum by me to deliniate the text I am typing into the Elastisearch search box.  I thought it might make it easier to be sure of exactly wah was being types rather than seeing bailey returns star or similar.

**Comment by kitenetter** [comment] 2019-05-20 11:44
@johnvanbreda I think Matt's original question related to the column-heading filter boxes, rather than to the more generic "Search" box, and the issue is that the behaviour of the column-heading filter boxes is different in the new verification grid than it was in the old, with regard to the use of wild cards.

Questions:
1. Is it going to be possible to set the new verification page to use wildcards in the same way as the old, for the column-head filter boxes?
2. Are we going to reinstate the "Create a filter" options on the new verification page, or are we intending to use the additional functionality available via the Search box instead of the "Create a filter" options?

The guidance that needs to be provided partly depends on the answers to those questions.

**Comment by MNSmith** [comment] 2019-05-20 16:12
I think the wildcard search is needed as it is more effective at defining the text to search for than the current Elastiseach facilities.  I really would like to see the *xxx* facility in searching column headers.

I would prefer to see the facility to create and save filters please, there are some filters I use regularly and it would be time consuming to have to redo multi column searches directly on the Grid each time.

**Comment by kitenetter** [comment] 2020-01-09 16:44
I'm not sure why I closed this, I think we do still need to clarify how the columnhead search boxes can work with wildcards.

**Comment by johnvanbreda** [comment] 2020-01-10 12:51
Switched to a simple_query_string ES search, using wildcards at ends of words automatically. Words don't have to be in correct order but other than that the results are similar to the original version.

**Comment by johnvanbreda** [comment] 2020-01-10 12:51
@kitenetter do you want to pick up saving of these filters as a separate issue?

**Comment by kitenetter** [comment] 2020-01-10 14:59
New issue added for filter saving.

The use of automatic wildcards at the end of words is probably a good thing most of the time, but I can foresee problems, e.g. I sometimes want to use column-head filters to select a set of records that have been recorded as genus only, and the auto-wildcard prevents that. But maybe that is a price worth paying for the ease of use more generally.

**Comment by johnvanbreda** [comment] 2020-01-10 15:26
@kitenetter I can easily remove the auto-wildcards if you prefer. The user can put * at the end of words manually instead?

**Comment by kitenetter** [comment] 2020-01-10 15:32
I think that does give us more flexibility. I'll make sure I mention it in the guidance/training documents.

**Comment by DavidHepper** [comment] 2020-01-10 16:15
Please let me know when changes such as auto-wildcarding change because I'll then have other docs to be updated.

**Comment by johnvanbreda** [comment] 2020-01-15 09:43
@DavidHepper I'm working on the release now. If you subscribe to notifications on this issue though you'll get a notification when it's closed.

**Comment by johnvanbreda** [comment] 2020-01-15 13:34
@DavidHepper just in case you didn't get notified...
Note that the hint on the text filter box at the top of the column has updated documentation that should help you.

**Closed** 2020-01-15 13:33 UTC
Labels: bug, code fixed awaiting release, feature request, verification
