### ISSUE TITLE
Photos shouldn't be so heavily compressed and resized during upload

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/iRecord#145] opened 2017-01-24 15:51 UTC
iRecord resizes and heavily compresses all uploaded images.  This currently results in a problematic loss of details needed for identification and also means that the retained images are suitable only for online display at small sizes.

Users of iRecord might have a reasonable expectation that the system would store submitted images at or near full quality.

I'm raising this issue in relation to the BSBI's New Year Plant Hunt, where a significant proportion of images submitted had been mangled to the point where identification of the taxon was impossible (when the original full-size image would often have been usable).

A second significant problem that we encountered was that essentially none of the images submitted via iRecord were usable for publicity purposes or as the basis for a reusable archive of plant photos.  Instead we had to rely on images that participants submitted to us directly or via social media (social media platforms do not compress or resize images to the same problematic extent as iRecord).

It seems a lost opportunity that iRecord is not archiving images at a reusable quality level.

For online use there is a need for low resolution thumbnails and preview images, but the original full size (or near full size) images should be retained.  Please could you review the level of compression applied.  My preference would be for jpegs to be archived at the submitted resolution (perhaps up to a maximum of ~ 10MB file size).

**Comment by johnvanbreda** [comment] 2017-01-25 12:28
Way back when we started accepting uploaded images from Indicia, we had lots of problems with people's internet connections not being fast enough for uploading the original resolution images. It was at best very slow, at worst they simply did not succeed. That's why we enabled the client side resizing of the images, so it is a compromise between practicality and the resulting quality of the images. The problem is of course exacerbated by having async download/upload speeds on broadband connections with upload being a lot slower than download - until recently uploading for example 50MB (about 8 images from my DSLR, not untypical for a 20 minute session photographing a few images) over my own home connection would have taken several minutes.

I note that Photobox has a website which allows you to upload full resolution images for integration into products you order. The code very quickly uploads a thumbnail, then leaves a JavaScript script running which uploads everything at full resolution. It can take ages but at least once the thumbnails are up you can start designing the product, though you can't leave the page.

Do we have a means of assessing the range of upload speeds our users have available to them?

**Comment by japonicus** [comment] 2017-01-25 13:16
Thanks, I'd not considered it from the perspective of upload speed (am probably too used to fast connections).  I suspect that for most users, upload speeds will have increased by more than an order of magnitude over the past decade, so that it would be worth relaxing the image constraints somewhat. 

Using background uploads that start as soon as an image is added would help with the perceived upload time - but I think that the user would still need to stay on the same page (was hoping that Web Workers would allow this to be circumvented, but I can't yet see a way).

Given the increasing prevalence of mobile recording apps that could easily be set to do protracted background transfers, might it be good to relax the restrictions on image sizes for the warehouse, even if the iRecord website forms continued to impose more stringent limits?

Another possible route to streamline large uploads might be to integrate with external cloud storage providers. I think that Dropbox (and probably also microsoft and google's equivalent services) provide api's allowing users to directly share files with an external website.  It might be a reasonable workflow for an iRecord user to upload images to e.g. Google Photos and share them with iRecord (which would retrieve a copy of the image directly from google's server). Am not quite sure how feasible this is yet.

Could you possibly have an opt-in trial allowing users with fast connections to upload larger images (without initially trying anything complex with background transfers, just relaxing the upload limits and compression level)? It might help gauge demand and assess how much of a problem upload speed still is.

**Comment by JimBacon** [comment] 2017-01-25 13:44
Are you talking about images submitted via the app? If so, is the degradation happening on the device rather than in iRecord? 

Where iRecord forms are used, images are scaled to 1500px maximum dimension in the browser. I don't recall there being server-side resizing.
The upload limit on the warehouse is currently 4MB.

**Comment by japonicus** [comment] 2017-01-25 14:05
@JimBacon I think that some of the specific problems with NYPH could in part have been due to over-stringent jpeg compression in the app, but there is also a problem with images sent via the iRecord website.  e.g. as a test I sent this moth image using the iRecord website.

Original image: https://www.dropbox.com/s/95hgqyxifxn9ajd/DSC_0549.JPG?dl=0 (9MB)
Once uploaded to irecord: http://warehouse1.indicia.org.uk/upload/o_1b78hakh01t261th3eqq1t8h1ojg8.jpg (124KB)

The image doesn't need to be 9MB but, by the time it's compressed to 124KB, too much detail is lost when zoomed in. (the image has also been transformed from 6000 x 4000 pixels to 1024 x 683 px)

The 4MB server-side cap on upload size can be problematic as it requires that client side code is capable of local image resizing (most images from modern DSLRs are larger than 4MB).  Users ran into problems when using a web based version of NYPH app, where I had reduced the amount of compression applied, so that the page was inadvertently attempting to send over-large images. That was a problem of my own making - but striking the right compromise between image size and detail is difficult.

**Comment by JimBacon** [comment] 2017-01-25 14:28
Which iRecord form did you use for the upload? The 1024px width is at odds with the 1500px limit I have seen.

**Comment by japonicus** [comment] 2017-01-25 14:30
'enter-casual-record'

the record is here:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=4450133

**Comment by JimBacon** [comment] 2017-01-25 14:42
On closer inspection I see that the resizeWidth and resizeHeight settings of 1500px are in the wrong place for that form. However, defaults of 1600px should then apply. Will need further investigation. Note there is also a resizeQuality option which is not being set.

**Comment by japonicus** [comment] 2017-01-25 15:00
I suspect that the client side uploader may be resizing to max of 1600px, but that there is then a server-side transformation applying the 1024px dimension
https://github.com/Indicia-Team/warehouse/blob/master/application/config/indicia_dist.php#L108

possibly
https://github.com/Indicia-Team/warehouse/blob/master/application/libraries/MY_Image.php#L41
which also applies a width of 1024px to the default image.

**Comment by johnvanbreda** [comment] 2017-01-25 15:01
@JimBacon There is a resize happening server side as well. In the application/config/indicia.php file, there is a $config['image_handling'] variable which sets the max width to 1024px for the default image size. We are resizing on the client once to help prevent slow uploads, then again on the server to prevent excessive disk use and to catch cases where the resize is not done on the client (e.g. some older browsers). 

We could potentially the server side resizing by specifying an empty array for the 'default' setting, or we could set it to something higher like width 3000.

**Comment by JimBacon** [comment] 2017-01-25 16:10
Not very clever of us to have the resize setting on the client larger than those on the server! Wasted bandwidth, wasted processing, and double mangling.

**Comment by kitenetter** [comment] 2020-08-11 18:27
@johnvanbreda do you know if any of the above issue still applies? I've not had any comments about over-compression of images recently - please close if you are happy with how things are set up.

**Comment by kitenetter** [comment] 2022-05-10 20:55
Closing.

**Closed by kitenetter** 2022-05-10 20:55 UTC
Labels: bug
