### ISSUE TITLE
Editing filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#207] opened 2017-05-09 12:05 UTC
I have a number of verification filters that need editing. This is an example:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=2315

The filter picks out 14 families of Hymenoptera. I need to add a further five families. But if I go to edit the filter and click on "What" I get taken to a screen that does not show the existing families. Adding a new family results in all 14 existing families being removed and just the new one remaining.

Is there any way of adding extra families to the existing list, or have I got to go back to square one and add all 19 families from scratch?

**Comment by johnvanbreda** [comment] 2017-07-11 13:31
Duplicate of #236. Now fixed.

**Closed by johnvanbreda** 2017-07-11 13:31 UTC
Labels: bug, question
