### ISSUE TITLE
Incoming iRecord App records show Lat/Long on verification grid

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#213] opened 2017-05-22 18:31 UTC
This problem seems to have appeared again, though it has been fixed in the past.

When loading onto the Verification Grid, records originating from the iRecord App have the geo-location displaying Lat/Long in the "Grid Ref" column, although the record itself does display the "Calculated Grid Reference".  Can we please have the geo-location for these set back to show the OS format "Calculated grid reference" in the "Grid Ref" column please.

**Comment by johnvanbreda** [comment] 2017-07-12 10:56
@kitenetter can you confirm - the grid ref shown in the verification grid should just be the output grid ref?

**Comment by japonicus** [comment] 2017-07-12 11:44
Could preferred display format (lat/lng or grid-reference) be a user-selected option?

**Comment by japonicus** [comment] 2017-07-12 11:54
per #253 I'd like there to be a way to indicate the type and precision of locations in the summarised results table. e.g. the BSBI's database distinguishes centroids with a symbol and with greying of 'over-precise' components of the grid-reference:
![cropped_centroid_display](https://user-images.githubusercontent.com/207360/28116348-a469e19c-6700-11e7-86cb-bd6a9bada8d7.png)

where SU8563 describes a monad square and NH6592390741 is a centroid of diameter 1000m

The detailed view shows: 
![cropped_centroid_display_detail](https://user-images.githubusercontent.com/207360/28116445-09e9d996-6701-11e7-9394-9f5df7eb7578.png)

which is shown on a map view as a 1km circle rather than as a square.

**Comment by kitenetter** [comment] 2017-07-18 16:42
@MNSmith could you clarify why you would prefer to see the grid ref in the verification grid? Personally I find it quite useful that the lat/long appears in the grid, alerting me to the record having originated from the app or from another non-grid input (as long as I can see the 'normal' grid ref in the details panel). I suspect that different verifiers may have different views on this so we'll need to assess the balance.

@japonicus I'm not sure which bit of iRecord you're referring to for user-selected options, Matt's original comment is in relation to verification only.

**Comment by japonicus** [comment] 2017-07-19 08:46
@kitenetter you're right, I had overlooked that Matt was referring to the verification grid rather than the public report pages, but I think the same issue applies to both.  What I'd envisaged was an option to select how a user prefers to view locations (whether as gridrefs or as lat/lng) - a choice affecting presentation rather than data entry.

I take your point that lat/long entries in the grid can be useful as a marker that the record is from an app, but I'm not sure that that can always be relied upon - the co-ordinate scheme used to return app records is an implementation detail and could change, or vary by app.  It might be better to have an explicit marker for records using a GPS'ed locality rather than a reference from a less dependable source.

Maybe I'm peculiar (probably) but I find it difficult to make any sense out of lat/lng references. I find grid-references a far easier format to work with.  Grid-refs are also more compact (the 3.s.f. lat/lng refs shown in iRecord tables are approximately equivalent to 100m precision: for southern England using 14 characters to display the same information contained in an 8 character grid-reference.

**Comment by MNSmith** [comment] 2017-07-19 12:15
Hi all

My query, as mentiond, refers only to the records on the Verification grid.  I'm with Tom here, I also find it impossible to make sense of Lat/Long refs and they take up a lot of space.  At least with OS grids I often have an idea of roughly which part of the work the record comes from and they are much, much easier to manipulate and analyse in terms of generating 10k/2k/1k "dots".

I really don't think it halps in any way to have lat/long grids present just so it is easy to say "this record came via an app".  One some of the verifcation grids I deal with we get records from mucltiple sources - apps, iRecord, dedicated Indicia forms on various websites.  If I want to see the source of a record I can look at the details in the "source ID" column of the grid.

Regards

Matt

____________________________________________________________________________________________________________________________________

Matthew Smith BSc (Hons) ARCS FRES MCIEEM
Consultant Ecologist
24 Allnatt Avenue
Winnersh
Berks
RG41 5AU

Tel: 0118 979 4313   Mob: 07710 160 690
  ----- Original Message -----

**Comment by JimBacon** [comment] 2017-07-19 12:22
For info, records can be submitted with lat/long via the iRecord website so it is not a clear indicator of a record from an app (though in likelihood it will be).

**Comment by kitenetter** [comment] 2017-07-19 12:29
Lat/longs are translated into grid refs wherever possible as part of the download process, so grid refs are always available (and I agree are much easier to work with than lat/longs in most circumstances). The question here is whether the verification gird should display native lat/longs if this is how the record has been originated, or whether the verification grid should by default display a translation of lat/longs into grid refs. 

If we go down that route (which I'd be happy to do) then the column in the verification grid that is currently headed "Grid ref" will change so that it is the equivalent of what we call "output grid ref" in the current CSV download format.

@johnvanbreda can you see any reason not to use output grid ref in the verification grid?

**Comment by johnvanbreda** [comment] 2017-07-19 13:44
@kitenetter no, I can see no reason not to use output_grid_ref. I doubt the verifier cares much about the format used by the inputter anyway and would prefer a consistent output format which is exactly what this field is for. Shall I do that?

**Comment by johnvanbreda** [comment] 2018-07-23 14:14
Closing as duplicate of #368.

**Closed** 2018-07-23 14:14 UTC
