### ISSUE TITLE
Media navigation buttons: unpredictable actions

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1162] opened 2021-10-12 17:17 UTC
Several verifiers have reported that the Prev and Next navigation arrows for moving between media items behave unpredictably. The three observed behaviours are: 
- Move to the prev/next photo cleanly;
- Move to the prev/next photo with a soft explosion effect around the photo;
- Zoom in/out the photo, as if the image itself had been clicked.

The active area is unexpectedly larger than the arrow 'button'.
The effects may or may not be dependent in some way on the size of the stored images.

Seen with FF 92. Example record: 21996464

**Comment by kitenetter** [comment] 2024-08-02 10:56
I can't reproduce this, which hopefully means that things have improved since 2021! Closing.

**Closed by kitenetter** 2024-08-02 10:56 UTC
