### ISSUE TITLE
ES verification: records missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#835] opened 2020-04-24 07:56 UTC
Roger Morris reports that there are several hundred records visible on his old verification page that are not available on his ES verification page. I can't see any obvious pattern to the missing ones - many are from the standard iRecord forms or from the app, while others are from non-iRecord sources. 

There are c.30 recent records showing on the old page, all of which seem to have been added yesterday, whereas the only pending records on the ES page are old ones.

But the vast majority of records on the old page are iNaturalist records that arrived from June 2019 to Jan 2020.

**Comment by kitenetter** [comment] 2020-04-24 09:25
Another verifier has reported that a redetermined record has not reappeared in his ES page 24 hours after redetermination, so possibly we have a more general issue with the ES page not refreshing properly?

**Comment by johnvanbreda** [comment] 2020-04-24 09:28
At least part of this problem is a backlog and at least part of the backlog is caused by my recent updates to fix a missing value for identification_difficulty in the cache tables. I've just upped the rate at which records are transferred across and I'll recheck this once the backlog is processed.

**Comment by kitenetter** [comment] 2020-04-24 17:14
Another report, at least some of which likely stems from the current backlog, although as with Roger's records there are some that seem to pre-date the current backlog.

> There are new sightings showing on the home page recent sightings and I have received a notification of them. The ‘new’ verification page does not show any, but when I eventually manage to get in to the old verification page ( sometimes times out before getting in ) there are 80 records to verify, some of which go back to 2011 and the last update date is showing back in January.
> 
> I have left the records as they are and would appreciate if: 
> It is possible to sort why records are not showing on the new page from time to time.
> Why I have just got records showing from 2011 which are showing to have been updated in January, why don’t they appear immediately for me to address?
>

**Comment by johnvanbreda** [comment] 2020-04-27 12:48
The backlog should be sorted now. As far as I can see from Roger's data this has picked up the older records.

**Closed by johnvanbreda** 2020-04-27 12:48 UTC
Labels: bug, verification

**Comment by DavidHepper** [comment] 2020-04-27 14:32
After the above fix at least one significant block of duplicates has appeared. I'm writing to my verifiers to ask that they complain promptly if anything imports without error but then fails to appear in Verify within a reasonable time. Some verifiers have been presuming that the import failed and then re-importing.
