### ISSUE TITLE
Verify - Disappearing records on VC boundaries

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#157] opened 2017-02-01 16:31 UTC
Some records for grid squares that span VC boundaries disappear in odd ways. 

**Examples** 
Records sitting on the VC23/VC22 boundary are 
4416450
4411207
4375922
These cannot be reviewed as they are invisible to the verifiers for VC23 (Stephen Burch) and VC22 (Mike Turton).

**Characterisation**
Since a recent release of iRecord (see #85) we can now see the VC(s) by name that iRecord has assigned to the record in the 'Localities' field of the Details pane. (The VC number uploaded by the observer/determiner/VCR for UK Odonata is only treated as a comment.)
The records above are marked by iRecord as ambiguous between VC23 and VC22. 'Localities' shows "Oxfordshire|Berkshire".
The problem lies with the matching in Verify of the records against the verifier's permitted VC list. 
- If the verifier is allowed to verify for both VCs (as only I may) and the 'Where' filter is set either cleared or set to (Oxfordshire + Berkshire) then the record appears **twice** in the grid (which is better than never.)
- If the verifier is allowed to verify for both VCs **and** the 'Where' filter is set for only one of (Oxfordshire | Berkshire) then the record does not appear in the grid.
- If the verifier is only allowed to verify for one of the VCs then the the record does not appear in the grid.

**Recommendations**
- The record should appear if any VC in Localities matches any VC that the user may verify.
- The duplication issue should be looked into as a lower priority - see #83.

**Comment by johnvanbreda** [comment] 2017-04-24 14:36
I've now done some investigation on this problem. The fundamental issue stems from the fact that having a single foreign key field to link a record to its vice county is about an order of magnitude faster than having a join table between records and the vice county locations when doing these filters. The problem is that the single foreign key field (as we have now) only allows a single vice county to be associated with each record, whereas a join table (which we also have but don't use in this circumstance because of performance) allows many to many.

Possible solutions:
1) Revert to using the index_locations_samples table (the join table) approach. This is easy to implement but will make vice county queries very slow.
2) Run a query to populate the missing vice county foreign keys with the single best match, i.e. the VC with the greatest overlap. This would need to be repeated or we could make it a regular part of the background processing. This is relatively easy to do, but means that you would see the record in either one or the other vice county list, not both. 
3) Change the datatype of the vice count foreign key field to an array datatype, allowing multiple values to be stored in one field. This approach would have the best outcome since performance is similar to the current setup and flexibilty to link a record to multiple VCs is maintained, but it is a lot of work, in the order of one or two days as a quick estimate.

My suggestion would be to a) write the query mentioned in 2 and run it. If the outcome is satisfactory, make it part of the background tasks so it is automated. If not, implement 3 as part of a bigger update.

Thoughts?

**Comment by DavidHepper** [comment] 2017-04-25 09:10
Option 2 is preferred, with the following comments in support: 
- I've no problem with it being _even randomly_ assigned to any one of the possible VCs for that location. 
- On which side of a river the sighting is made doesn't matter in the great scheme of things. It is far more important that at least one Verifier can see the record than worry about a few tens of metres of position.
- Our Verifiers work co-operatively - honestly. In some cases e.g. East/West Kent one Verifier handles both but this problem causes records on the boundary not to be seen. 
- Ideally the Verifier should choose which VC the record belongs to, by being able to edit the field. 
- Records from BDS imports already have a custom field containing a VC number. Currently this is treated only as a comment. The code could look at this and accept it as arbiter only if it is matches one of the list derived by iRecord's own processing. However, I appreciate that this involves digging into custom fields so might be unacceptable.
- Surely the "background processing" to determine the VC would only need to be re-run if the geolocation value is edited? The VC is already computed by a background process - see #156.
David

**Comment by DavidRoy** [comment] 2017-04-25 12:52
I support option 2 as an immediate fix.

The ability for the verifier to edit the VC assignment should be available at some point.  For many schemes, the VC assignment is highly valued (i.e. what side of the river is more important for immobile species such as plants).

**Comment by kitenetter** [comment] 2017-04-25 12:59
Another option 2 vote from me. It would be good to develop a means for verifiers to re-assign vice-counties otherwise we run the risk of people rejecting valid records simply in order to remove them from the verification grid. Perhaps the VC allocation tool that is being developed for BSBI could be used here as well?

**Comment by johnvanbreda** [comment] 2017-04-25 14:08
I've run a query to fix the existing data as suggested in point 2. Here's the query for reference:
```
select distinct on (s.id) s.id as sample_id, ils.location_id
into temporary to_fix
from cache_samples_functional s
join index_locations_samples ils on ils.sample_id=s.id and ils.location_type_id=15
where s.location_id_vice_county is null
order by s.id;

update cache_samples_functional s
set location_id_vice_county = f.location_id
from to_fix f
where s.id=f.sample_id
and s.location_id_vice_county is null;

update cache_occurrences_functional o
set location_id_vice_county=s.location_id_vice_county
from cache_samples_functional s
where s.id=o.sample_id
and s.location_id_vice_county is not null
and o.location_id_vice_county is null;
```

If I can have confirmation that this approach has worked OK, then I'll integrate these steps in the background tasks (i.e. the spatial_index_builder). 

@kitenetter Yes I think a longer term solution would be to integrate the ideas developed for the BSBI form into the verification page, only for records that straddle a boundary. Then a verifier could force a record into the correct VC.

**Comment by DavidRoy** [comment] 2017-04-25 14:13
Thanks.  Will this assign the majority VC based on the gridref.  It's not obvious to me from the SQL that this is happening

**Comment by johnvanbreda** [comment] 2017-06-08 13:03
The query above does not assign the majority VC on the basis of the grid ref overlap, but I have now implemented a solution which does. Closing this now but see #220 about fixing remaining issues with gaps in the indexing.

**Comment by kitenetter** [comment] 2018-04-12 17:40
@johnvanbreda this problem has re-occurred - @DavidHepper reports:

> A while ago John fixed the long-standing problem of assignment of a VC to squares straddling VC borders that solved the problem. It appears to be back! Example IDs: 6591780 and 6591784, imported on 30/03, both showing Locality as "West Gloucestershire|East Gloucestershire", such that if a filter is set on these two VCs the records are not shown in the grid. They are only seen in Verify if the Where condition is blank and the user (e.g. me) has verify rights to all VCs. I'm prevented from marking the whole import as Accepted until I can see these - about 200 records out of 1,000 within this one import are affected.

**Comment by DavidHepper** [comment] 2018-05-03 12:43
Please could this be fixed again as a matter of urgency? It is alarming when records simply disappear.

**Comment by johnvanbreda** [comment] 2018-05-03 15:10
Should now be fixed. It was actually a slightly different problem caused by some corrupt polygons in the locations on the warehouse. Because the records are batched, any error in the batch left the record in this unindexed state even if the record itself and its location was not corrupt.

I've done the following:
1) Update the code to enforce valid polygons when they are added to the system.
2) Applied a script which fixed any existing polygons:
```
select * into temporary tofix from locations where st_isvalid(boundary_geom)=false;
update locations set boundary_geom=st_makevalid(boundary_geom) where id in (select id from tofix);
drop table tofix;

select * into temporary tofix from samples where st_isvalid(geom)=false;
update samples set geom=st_makevalid(geom) where id in (select id from tofix);
drop table tofix;

select * into temporary tofix from cache_occurrences_functional where st_isvalid(public_geom)=false;
update cache_occurrences_functional set public_geom=st_makevalid(public_geom) where id in (select id from tofix);
drop table tofix;

select * into temporary tofix from cache_samples_functional where st_isvalid(public_geom)=false;
update cache_samples_functional set public_geom=st_makevalid(public_geom) where id in (select id from tofix);
drop table tofix;
```

3) Applied a script which linked any records that should have been linked but weren't:
```

SELECT distinct o.sample_id as id INTO temporary smplist 
FROM cache_occurrences_functional o
JOIN index_locations_samples ils on ils.sample_id=o.sample_id AND ils.location_type_id=15
WHERE o.location_id_vice_county IS NULL;

DROP TABLE IF EXISTS overlapping_boundaries;

SELECT s.website_id, s.survey_id, s.id AS sample_id, ils.location_id, 0::float AS area
INTO TEMPORARY overlapping_boundaries
FROM cache_samples_functional s
JOIN index_locations_samples ils ON ils.sample_id=s.id AND ils.location_type_id=15 
JOIN locations l ON l.id=ils.location_id and l.deleted=false AND COALESCE(l.code, '') NOT LIKE '%+%'
JOIN smplist slist ON slist.id=ils.sample_id;

UPDATE overlapping_boundaries ob
SET area=st_area(st_intersection(s.geom, l.boundary_geom))
FROM samples s, locations l
WHERE s.id=ob.sample_id AND l.id=ob.location_id
AND s.deleted=false
AND l.deleted=false;

DELETE FROM overlapping_boundaries WHERE area=0;

DELETE from overlapping_boundaries ob1
USING overlapping_boundaries ob2
WHERE ob2.sample_id=ob1.sample_id
AND (ob2.area>ob1.area OR (ob2.area=ob1.area AND ob2.location_id<ob1.location_id));

UPDATE cache_occurrences_functional o
SET location_id_vice_county = ob.location_id
FROM overlapping_boundaries ob
WHERE o.website_id=ob.website_id AND o.survey_id=ob.survey_id AND o.sample_id=ob.sample_id
AND COALESCE(o.location_id_vice_county, 0)<>ob.location_id;

UPDATE cache_samples_functional s
SET location_id_vice_county = ob.location_id
FROM overlapping_boundaries ob
WHERE s.website_id=ob.website_id AND s.survey_id=ob.survey_id AND s.id=ob.sample_id
AND COALESCE(s.location_id_vice_county, 0)<>ob.location_id;

DROP TABLE overlapping_boundaries;
```

**Closed by johnvanbreda** 2018-05-03 15:10 UTC
Labels: bug

**Comment by DavidHepper** [comment] 2018-05-03 15:50
Thank you! 143 have just appeared for E. & W. Glos. We'll do a bulk verify and go looking for trouble.
