### ISSUE TITLE
Viewing of record photos - changes to the old display method.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#1055] opened 2021-05-14 18:26 UTC
An update today has changed the way record photos are displayed, they now "pop up" and occupy the whole screen, which means if I want to go back to the record and verify it I have to close the photo window.  I find this is slowing down my verification a fair bit, as well as requiring "extra clicks" to process a record.

 I would much prefer to see the photo at first instance just occupy the area where the map is displayed so the verification radio buttons are still visible and can be clicked on after a look at the photo . If I want to see the photo any larger clicking on it should then take it to "full screen".  This means I can look at a photo and then verify the record much faster.  Is it possible to set the photo to display in this "2 stage" manner.

**Comment by kitenetter** [comment] 2021-05-14 18:40
@MNSmith This is part of some updates that will enable you to verify the records using keyboard controls, which should avoid the need to return to the main page to click on the verification icons. There's some more information here:
https://www.brc.ac.uk/irecord/resources-verify

At the moment the keyboard verification is not yet working (on my computer at least) but it is on the way.

**Comment by kitenetter** [comment] 2021-05-14 19:00
Keyboard shortcuts are now working on my computer.

**Comment by MNSmith** [comment] 2021-05-14 19:54
Thanks for the update.  However, if the Keyboard numeric keys 1-5 are enabled so as to allow us to use the 5 verification buttons then:
a) the number pad keys need to be similarly enabled and 
b) the numeric key options should be extended to cover the full range of verification functions, so 6-9 should be enabled to allow the Query, Edit and Redet functions etc to be accessed

**Comment by kitenetter** [comment] 2021-05-14 20:03
Query is available by typing "Q" and redet by "R". I see editing a record as a last resort (due to the risks of unintentionally editing records for multiple taxa) so am less keen on providing a shortcut option for that.

I agree that the ability to use the number pad keys would be helpful.

**Comment by MNSmith** [comment] 2021-05-14 20:06
[OK, hold off on enabling the Edit function then.  On the basis on being left handed - ie the mouse is in my left hand so my "spare" hand is on the number pad, I'd much prefer that the "Q" and "R" functions be acessible from the num pad as well]

Even with the keyboard features fully enabled as requested above, I would still like the image size to be modified from the current default "full screen" to something smaller.  At the moment you either have a choice of "image" or "details", and often when reviewing you need to look at both.  If the photo could only display such that it only covered the grid and not the detail pane as well, leaving both the map and the details pane visible, that would very much impove things and make the use of keyboard shortcuts much more "user friendly".

This please:

![Image2](https://user-images.githubusercontent.com/18451743/118322967-d8abed80-b4f7-11eb-876d-e661c9129f6e.jpg)

**Comment by kitenetter** [comment] 2021-05-14 20:13
Thanks @MNSmith 

The previous way of handling photos also obscured the record details to a degree, but it was less opaque. We will see if we can move back in that direction.

**Comment by DavidHepper** [comment] 2021-05-15 10:21
How about giving the window for the photo its own controls for size and position? And remember these for the user or at least for the session?

**Comment by johnvanbreda** [comment] 2021-05-15 17:07
I've done the following:
1. Reduce the background opacity when viewing an image, so it's easier to see the details.
2. i key now opens and closes an image (toggles)
3. Number pad keys work for verification statuses as long as numlock is on.

For obvious reasons, I'm keen to leverage the functionality of the image popup library we are using rather than implement something completely unique here. Having said that we could probably do something to align the image popup so it obscures the grid rather than the details + map. Or possibly something within the grid itself so the selected row's photos show at a larger intermediary size, negating the need to zoom in for records that can be confirmed from a mid-sized image.

**Comment by kitenetter** [comment] 2021-06-01 10:14
@johnvanbreda I'm seeing a change in the behaviour of the "i" key to open images, where there are multiple images for an occurrence.

- If I press "i" to open the images, then continue pressing "i", the display cycles once through the images and then closes them.
- If I press "i" to open the images, then use the arrow keys to cycle through the images, I can go round the cycle multiple times. But if I then press "i" again, I have to press "i" repeatedly to close each individual image, rather than being able to close them all down in one go (or alternatively I can use "Esc" to close down in one go)

It feels quite odd having to close down each image individually with the "i" key following use of the arrow keys, but if this is the intended behaviour then I think what I need to do is to get used to just using the "i" key and not use the arrow keys at all. That's probably fine and if you can confirm that this is the intended behaviour I will update the guidance for the keyboard shortcuts. 

Is there a case for disabling the arrow keys for photo display/navigation, and only allowing the "i" key, to avoid confusion?

**Comment by johnvanbreda** [comment] 2021-06-01 16:00
I would actually expect the i key to act as a show/hide shortcut and the arrow keys to be used for navigation. I think it's cleaner and more obvious that way (plus I don't really want to mess with the FancyBox internals which already handles the arrow keys). I've changed the code to fix the duplication of images that was occurring on the i key.

**Comment by kitenetter** [comment] 2021-06-15 11:14
I think we can close this.

**Closed by kitenetter** 2021-06-15 11:14 UTC
Labels: verification
