### ISSUE TITLE
Verification page failing to refresh

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1349] opened 2022-09-05 10:03 UTC
Several verifiers have reported to @robin-hutchinson that if they verify a record, the record is staying on the verification grid and apparently not changing, although I think in most cases the verification decision is being applied, it's just not refreshing on the verification page.

I've just replicated this with my own verification page:
- Open page and reject the first record
- Nothing appears to happen, the record stays in the grid, but the rejection has been applied: https://irecord.org.uk/record-details?occurrence_id=27980385
- If I sort the grid, or refresh the page, the record gets removed from the pending view.

So it looks like it is just the grid view update that is failing.

**Comment by johnvanbreda** [comment] 2022-09-05 10:32
@kitenetter does this only happen on rejection, or does it happen on accepting a record too? Also, which browser?

**Comment by robin-hutchinson** [comment] 2022-09-05 10:34
@johnvanbreda I have found the issue using "Accepted as Considered Correct", and using Microsoft Edge

**Comment by kitenetter** [comment] 2022-09-05 10:34
I was using Chrome, and only tried a rejection. I think the other verifiers were accepting records.

**Comment by johnvanbreda** [comment] 2022-09-05 11:22
I can't reproduce this in Edge or Chrome. When I verify a record it immediately greys out and the next record is selected, then once the verification is completed in the background the greyed-out record is removed from the grid. 

Can you check the Console tab on your browser's Developer Tools (Ctrl-Shift-I) to see if there are any errors please?

**Comment by kitenetter** [comment] 2022-09-05 11:41
I'm no longer able to reproduce this in Chrome. The records are now getting greyed out as expected. Will monitor later today to see if the problem re-occurs.

@robin-hutchinson looks like this might be difficult to pin down. Are you still getting problems in Edge?

**Comment by robin-hutchinson** [comment] 2022-09-05 11:48
@kitenetter I tried using my own account and did not experience any issues, but I am still seeing the same issue when masquerading as user ID 83948

In the console, this error appeared: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.

**Comment by robin-hutchinson** [comment] 2022-09-05 11:50
This user did specify they were having trouble with a specific group of uploaded records, which all come from the website/survey "141|682", in case that is useful information.

**Comment by robin-hutchinson** [comment] 2022-09-05 13:11
I've just sent a message asking for the decisions the verifier would like to make on some of their pending records, I will email you once I have these so that you can verify them.

**Comment by kitenetter** [comment] 2022-09-06 09:24
Another report from a verifier this morning:
"I also found that when I ticked a batch of those records as "Accepted" (or in some cases "rejected") and clicked the "save" button, the records did not move off the screen. I found however that if I switched to the other vice-county, and then back to the first one, the records had in fact cleared and were no longer showing on the screen, so I had to go through them constantly switching from one vice-county to the other and back again. I am still having this problem up to this morning, when again there was quite a long list (though nothing like as long as last Friday's) in VC59. Is there some fault with iRecord that is causing this, please?"

I think the records concerned are also Garden Butterfly Survey records, although I can't see why that particular source would be causing problems on the verification page.

**Comment by johnvanbreda** [comment] 2022-09-06 10:38
Thanks - I think I see the problem now, which relates to the records being marked as private sites. I'll post a fix when it's ready.

**Closed** 2022-09-06 10:45 UTC
Labels: bug, urgent, verification

**Comment by johnvanbreda** [comment] 2022-09-06 10:57
Now fixed. Any sensitive or private record would have had the same problem, but the GBS dataset is particularly affected as all the gardens are private sites.

**Comment by robin-hutchinson** [comment] 2022-09-06 11:05
Thank you very much John, I've verified some records successfully as well, I'll email to let the verifier know.
