### ISSUE TITLE
Date format incorrect on Import?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#704] opened 2019-10-28 18:22 UTC
Have the rules for Date format changed from the usual DD/MM/YYYY ? I'm trying to import a single record in Training Mode: 
[3a. Bedfordshire to 2018 - tidied - 1st row only.txt](https://github.com/BiologicalRecordsCentre/iRecord/files/3780050/3a.Bedfordshire.to.2018.-.tidied.-.1st.row.only.txt)

The import uses the following parameters:
![image](https://user-images.githubusercontent.com/24915271/67704499-219b6000-f9ad-11e9-94e1-ef7d208e7f45.png)

The CSV has column headings and only the columns that automatically match are imported.
This record appears to have imported correctly except for the Date field: **08/04/2014** in the CSV but imported as **2001** (year only).

Imported record ID: 12056137

Am I being a numpty?

**Comment by kitenetter** [comment] 2019-10-31 12:06
I'm not aware of any change @DavidHepper (and I'm sure you're not being a numpty!). Will add to our issues review next Tuesday.

**Comment by DavidHepper** [comment] 2019-10-31 12:58
Thanks. Any chance of a quick look earlier? I've 11,000 records to import for Bedfordshire. Also tried date format **2014-04-08** but the result was the same.

**Comment by kitenetter** [comment] 2019-10-31 13:56
@DavidHepper I have a possible solution, although I don't understand why it is needed. The first column in your file is headed "entry" and contains the number 1. When that column is present, iRecord appears to be interpreting 1 as 2001, even though the first column is set not to be imported.

If I delete the "entry" column, leaving Date as the first column, and run the import again, the date is handled correctly and all works as expected.

I can confirm that there has been no change to the date formatting rules, and that the DR import uses the same date attribute as most other iRecord datasets.

My speculation is that something odd is going on with the use of double quotes around the column headings and/or data. But I have no idea if that is the explanation.

I'm not sure if you need to import the "entry" column. If not I would suggest deleting it for this data file. If you do, I would suggest re-ordering it so that "entry" appears as the final column (haven't tested that but worth a try if needed).

**Comment by kitenetter** [comment] 2019-10-31 14:01
Further to this, if I import a record that has "2" in the first "entry" column it gets interpreted as a date of 2002.

**Comment by DavidHepper** [comment] 2019-10-31 15:59
A column that is marked as Not Imported is corrupting the next field along? That's truly bizarre. I've removed the 'entry' column and it all works. I really think this bug ought to be found and suggest:
- Is there something magic about the column header name 'entry'?
- Is the problem caused by the skipped column being the first column in the sheet?
- Is a skipped column always a problem when it is just ahead of a Date column?
- I doubt it's related to the double quotes.

**Comment by kitenetter** [comment] 2020-01-09 20:56
@DavidHepper do you know if this isue is still a problem, or has it gone away since the changes John made under #717 ?

I'm going to close the issue for now but will of course reopen if needed.

**Closed by kitenetter** 2020-01-09 20:56 UTC
Labels: bug
