### ISSUE TITLE
New photo layout not scrolling correctly

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#1063] opened 2021-05-20 18:10 UTC
On the verification screen, the new photo layout is now not scrolling correctly, where it was previously.

For a record with multiple photos, if I click on the photo I get a photo pop up.  However, the left / right scroll arrow keys do not scroll the photo on to the next / previous photo in the set.  Instead, the displayed photo "zooms" slightly and clicking on the arrow again causes it to "unzoom".

**Comment by johnvanbreda** [comment] 2021-05-21 09:00
@kitenetter can you reproduce this? I've tried Edge, Chrome and Firefox with no luck.

**Comment by kitenetter** [comment] 2021-05-21 09:39
I can't reproduce it on Firefox.

@MNSmith which browser are you using?

**Comment by MNSmith** [comment] 2021-05-21 10:42
Just tried the photos again this morning and am seeing the same behaviour with the photos.  I'm using Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Windows 7.

**Comment by kitenetter** [comment] 2021-05-21 11:04
I've just tried on exactly the same version of Chrome and the photos are behaving normally for me.

**Comment by johnvanbreda** [comment] 2021-05-21 11:04
It works OK for me too. @MNSmith perhaps you can clarify the exact sequence of mouse clicks and key strokes leading to the problem, to make sure we are doing the same thing?

**Comment by kitenetter** [comment] 2021-06-15 11:05
This appears to have resolved itself? Closing.

**Closed by kitenetter** 2021-06-15 11:05 UTC
